// AUTO-GENERATED by scripts/build-marketplace-shards.ts — do not edit.
import type { LocationEntry } from "./types";

export const ENTRIES: LocationEntry[] = [
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-aalen",
      "place": "Aalen",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Aalen, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-aachen",
        "keyword": "Buy Antminer Z15 Pro in Aachen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-aschaffenburg",
        "keyword": "Buy Antminer Z15 Pro in Aschaffenburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-augsburg",
        "keyword": "Buy Antminer Z15 Pro in Augsburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-baden-baden",
        "keyword": "Buy Antminer Z15 Pro in Baden-Baden, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bamberg",
        "keyword": "Buy Antminer Z15 Pro in Bamberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bayreuth",
        "keyword": "Buy Antminer Z15 Pro in Bayreuth, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bergisch-gladbach",
        "keyword": "Buy Antminer Z15 Pro in Bergisch Gladbach, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mainz",
        "keyword": "Buy Antminer Z15 Pro in Mainz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mannheim",
        "keyword": "Buy Antminer Z15 Pro in Mannheim, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-marburg",
        "keyword": "Buy Antminer Z15 Pro in Marburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mönchengladbach",
        "keyword": "Buy Antminer Z15 Pro in Mönchengladbach, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mülheim-an-der-ruhr",
        "keyword": "Buy Antminer Z15 Pro in Mülheim an der Ruhr, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-krefeld",
      "place": "Krefeld",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Krefeld, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-kiel",
        "keyword": "Buy Antminer Z15 Pro in Kiel, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-koblenz",
        "keyword": "Buy Antminer Z15 Pro in Koblenz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-konstanz",
        "keyword": "Buy Antminer Z15 Pro in Konstanz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-landshut",
        "keyword": "Buy Antminer Z15 Pro in Landshut, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leipzig",
        "keyword": "Buy Antminer Z15 Pro in Leipzig, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leverkusen",
        "keyword": "Buy Antminer Z15 Pro in Leverkusen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lingen",
        "keyword": "Buy Antminer Z15 Pro in Lingen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-saarbrücken",
        "keyword": "Buy Antminer Z15 Pro in Saarbrücken, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salzgitter",
        "keyword": "Buy Antminer Z15 Pro in Salzgitter, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schweinfurt",
        "keyword": "Buy Antminer Z15 Pro in Schweinfurt, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schwerin",
        "keyword": "Buy Antminer Z15 Pro in Schwerin, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-siegen",
        "keyword": "Buy Antminer Z15 Pro in Siegen, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lingen",
      "place": "Lingen",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lingen, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-landshut",
        "keyword": "Buy Antminer Z15 Pro in Landshut, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leipzig",
        "keyword": "Buy Antminer Z15 Pro in Leipzig, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leverkusen",
        "keyword": "Buy Antminer Z15 Pro in Leverkusen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ludwigsburg",
        "keyword": "Buy Antminer Z15 Pro in Ludwigsburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ludwigshafen",
        "keyword": "Buy Antminer Z15 Pro in Ludwigshafen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lübeck",
        "keyword": "Buy Antminer Z15 Pro in Lübeck, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lüneburg",
        "keyword": "Buy Antminer Z15 Pro in Lüneburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-magdeburg",
        "keyword": "Buy Antminer Z15 Pro in Magdeburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mainz",
        "keyword": "Buy Antminer Z15 Pro in Mainz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mannheim",
        "keyword": "Buy Antminer Z15 Pro in Mannheim, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-marburg",
        "keyword": "Buy Antminer Z15 Pro in Marburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mönchengladbach",
        "keyword": "Buy Antminer Z15 Pro in Mönchengladbach, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-münster",
      "place": "Münster",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Münster, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-mönchengladbach",
        "keyword": "Buy Antminer Z15 Pro in Mönchengladbach, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mülheim-an-der-ruhr",
        "keyword": "Buy Antminer Z15 Pro in Mülheim an der Ruhr, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-münchen",
        "keyword": "Buy Antminer Z15 Pro in München, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neubrandenburg",
        "keyword": "Buy Antminer Z15 Pro in Neubrandenburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neumünster",
        "keyword": "Buy Antminer Z15 Pro in Neumünster, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neuss",
        "keyword": "Buy Antminer Z15 Pro in Neuss, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nürnberg",
        "keyword": "Buy Antminer Z15 Pro in Nürnberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bottrop",
        "keyword": "Buy Antminer Z15 Pro in Bottrop, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brandenburg-an-der-havel",
        "keyword": "Buy Antminer Z15 Pro in Brandenburg an der Havel, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-braunschweig",
        "keyword": "Buy Antminer Z15 Pro in Braunschweig, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bremen",
        "keyword": "Buy Antminer Z15 Pro in Bremen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bremerhaven",
        "keyword": "Buy Antminer Z15 Pro in Bremerhaven, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-steyr",
      "place": "Steyr",
      "country": "Austria",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Steyr, Austria"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-salzburg",
        "keyword": "Buy Antminer Z15 Pro in Salzburg, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sankt-pölten",
        "keyword": "Buy Antminer Z15 Pro in Sankt Pölten, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schwechat",
        "keyword": "Buy Antminer Z15 Pro in Schwechat, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ternitz",
        "keyword": "Buy Antminer Z15 Pro in Ternitz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traiskirchen",
        "keyword": "Buy Antminer Z15 Pro in Traiskirchen, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traun",
        "keyword": "Buy Antminer Z15 Pro in Traun, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vienna",
        "keyword": "Buy Antminer Z15 Pro in Vienna, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bludenz",
        "keyword": "Buy Antminer Z15 Pro in Bludenz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-braunau-am-inn",
        "keyword": "Buy Antminer Z15 Pro in Braunau am Inn, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bregenz",
        "keyword": "Buy Antminer Z15 Pro in Bregenz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dornbirn",
        "keyword": "Buy Antminer Z15 Pro in Dornbirn, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-eisenstadt",
        "keyword": "Buy Antminer Z15 Pro in Eisenstadt, Austria"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-kalgoorlie",
      "place": "Kalgoorlie",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Kalgoorlie, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-goulburn",
        "keyword": "Buy Antminer Z15 Pro in Goulburn, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hervey-bay",
        "keyword": "Buy Antminer Z15 Pro in Hervey Bay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hobart",
        "keyword": "Buy Antminer Z15 Pro in Hobart, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-karratha",
        "keyword": "Buy Antminer Z15 Pro in Karratha, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-launceston",
        "keyword": "Buy Antminer Z15 Pro in Launceston, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mackay",
        "keyword": "Buy Antminer Z15 Pro in Mackay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mandurah",
        "keyword": "Buy Antminer Z15 Pro in Mandurah, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-canberra",
        "keyword": "Buy Antminer Z15 Pro in Canberra, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-central-coast",
        "keyword": "Buy Antminer Z15 Pro in Central Coast, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cessnock",
        "keyword": "Buy Antminer Z15 Pro in Cessnock, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-charters-towers",
        "keyword": "Buy Antminer Z15 Pro in Charters Towers, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-coffs-harbour",
        "keyword": "Buy Antminer Z15 Pro in Coffs Harbour, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-swan-hill",
      "place": "Swan Hill",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Swan Hill, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-rockhampton",
        "keyword": "Buy Antminer Z15 Pro in Rockhampton, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shepparton",
        "keyword": "Buy Antminer Z15 Pro in Shepparton, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sunshine-coast",
        "keyword": "Buy Antminer Z15 Pro in Sunshine Coast, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sydney",
        "keyword": "Buy Antminer Z15 Pro in Sydney, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tamworth",
        "keyword": "Buy Antminer Z15 Pro in Tamworth, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-toowoomba",
        "keyword": "Buy Antminer Z15 Pro in Toowoomba, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-townsville",
        "keyword": "Buy Antminer Z15 Pro in Townsville, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cairns",
        "keyword": "Buy Antminer Z15 Pro in Cairns, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-canberra",
        "keyword": "Buy Antminer Z15 Pro in Canberra, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-central-coast",
        "keyword": "Buy Antminer Z15 Pro in Central Coast, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cessnock",
        "keyword": "Buy Antminer Z15 Pro in Cessnock, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-charters-towers",
        "keyword": "Buy Antminer Z15 Pro in Charters Towers, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-vianden",
      "place": "Vianden",
      "country": "Luxembourg",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Vianden, Luxembourg"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-schifflange",
        "keyword": "Buy Antminer Z15 Pro in Schifflange, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-steinfort",
        "keyword": "Buy Antminer Z15 Pro in Steinfort, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-strassen",
        "keyword": "Buy Antminer Z15 Pro in Strassen, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wiltz",
        "keyword": "Buy Antminer Z15 Pro in Wiltz, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-remich",
        "keyword": "Buy Antminer Z15 Pro in Remich, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rumelange",
        "keyword": "Buy Antminer Z15 Pro in Rumelange, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bettembourg",
        "keyword": "Buy Antminer Z15 Pro in Bettembourg, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-clervaux",
        "keyword": "Buy Antminer Z15 Pro in Clervaux, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dudelange",
        "keyword": "Buy Antminer Z15 Pro in Dudelange, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-echternach",
        "keyword": "Buy Antminer Z15 Pro in Echternach, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-esch-sur-alzette",
        "keyword": "Buy Antminer Z15 Pro in Esch-sur-Alzette, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ettelbruck",
        "keyword": "Buy Antminer Z15 Pro in Ettelbruck, Luxembourg"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-pavlohrad",
      "place": "Pavlohrad",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Pavlohrad, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-mykolaiv",
        "keyword": "Buy Antminer Z15 Pro in Mykolaiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nizhyn",
        "keyword": "Buy Antminer Z15 Pro in Nizhyn, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-odesa",
        "keyword": "Buy Antminer Z15 Pro in Odesa, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-poltava",
        "keyword": "Buy Antminer Z15 Pro in Poltava, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rivne",
        "keyword": "Buy Antminer Z15 Pro in Rivne, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sevastopol",
        "keyword": "Buy Antminer Z15 Pro in Sevastopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shostka",
        "keyword": "Buy Antminer Z15 Pro in Shostka, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kovel",
        "keyword": "Buy Antminer Z15 Pro in Kovel, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kremenchuk",
        "keyword": "Buy Antminer Z15 Pro in Kremenchuk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kryvyi-rih",
        "keyword": "Buy Antminer Z15 Pro in Kryvyi Rih, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyiv",
        "keyword": "Buy Antminer Z15 Pro in Kyiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-volodymyr",
      "place": "Volodymyr",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Volodymyr, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-ternopil",
        "keyword": "Buy Antminer Z15 Pro in Ternopil, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-uzhhorod",
        "keyword": "Buy Antminer Z15 Pro in Uzhhorod, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vinnytsia",
        "keyword": "Buy Antminer Z15 Pro in Vinnytsia, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-yalta",
        "keyword": "Buy Antminer Z15 Pro in Yalta, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zaporizhzhia",
        "keyword": "Buy Antminer Z15 Pro in Zaporizhzhia, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zhytomyr",
        "keyword": "Buy Antminer Z15 Pro in Zhytomyr, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khmelnytskyi",
        "keyword": "Buy Antminer Z15 Pro in Khmelnytskyi, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khmilnyk",
        "keyword": "Buy Antminer Z15 Pro in Khmilnyk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khorol",
        "keyword": "Buy Antminer Z15 Pro in Khorol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kiev",
        "keyword": "Buy Antminer Z15 Pro in Kiev, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kirovohrad",
        "keyword": "Buy Antminer Z15 Pro in Kirovohrad, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kovel",
        "keyword": "Buy Antminer Z15 Pro in Kovel, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-anapa",
      "place": "Anapa",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Anapa, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-abakan",
        "keyword": "Buy Antminer Z15 Pro in Abakan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-achinsk",
        "keyword": "Buy Antminer Z15 Pro in Achinsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arkhangelsk",
        "keyword": "Buy Antminer Z15 Pro in Arkhangelsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-armavir",
        "keyword": "Buy Antminer Z15 Pro in Armavir, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-astrakhan",
        "keyword": "Buy Antminer Z15 Pro in Astrakhan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-balakovo",
        "keyword": "Buy Antminer Z15 Pro in Balakovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-barnaul",
        "keyword": "Buy Antminer Z15 Pro in Barnaul, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-stavropol",
        "keyword": "Buy Antminer Z15 Pro in Stavropol, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sterlitamak",
        "keyword": "Buy Antminer Z15 Pro in Sterlitamak, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-surgut",
        "keyword": "Buy Antminer Z15 Pro in Surgut, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-syktyvkar",
        "keyword": "Buy Antminer Z15 Pro in Syktyvkar, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tambov",
        "keyword": "Buy Antminer Z15 Pro in Tambov, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-khimki",
      "place": "Khimki",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Khimki, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-kazan",
        "keyword": "Buy Antminer Z15 Pro in Kazan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kemerovo",
        "keyword": "Buy Antminer Z15 Pro in Kemerovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khabarovsk",
        "keyword": "Buy Antminer Z15 Pro in Khabarovsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kostroma",
        "keyword": "Buy Antminer Z15 Pro in Kostroma, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krasnodar",
        "keyword": "Buy Antminer Z15 Pro in Krasnodar, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krasnoyarsk",
        "keyword": "Buy Antminer Z15 Pro in Krasnoyarsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kurgan",
        "keyword": "Buy Antminer Z15 Pro in Kurgan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-moscow",
        "keyword": "Buy Antminer Z15 Pro in Moscow, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-murmansk",
        "keyword": "Buy Antminer Z15 Pro in Murmansk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mytishchi",
        "keyword": "Buy Antminer Z15 Pro in Mytishchi, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-naberezhnye-chelny",
        "keyword": "Buy Antminer Z15 Pro in Naberezhnye Chelny, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nakhodka",
        "keyword": "Buy Antminer Z15 Pro in Nakhodka, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-novokuznetsk",
      "place": "Novokuznetsk",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Novokuznetsk, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-nizhny-novgorod",
        "keyword": "Buy Antminer Z15 Pro in Nizhny Novgorod, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nizhny-tagil",
        "keyword": "Buy Antminer Z15 Pro in Nizhny Tagil, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-norilsk",
        "keyword": "Buy Antminer Z15 Pro in Norilsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-novorossiysk",
        "keyword": "Buy Antminer Z15 Pro in Novorossiysk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-novosibirsk",
        "keyword": "Buy Antminer Z15 Pro in Novosibirsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-omsk",
        "keyword": "Buy Antminer Z15 Pro in Omsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-orenburg",
        "keyword": "Buy Antminer Z15 Pro in Orenburg, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-armavir",
        "keyword": "Buy Antminer Z15 Pro in Armavir, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-astrakhan",
        "keyword": "Buy Antminer Z15 Pro in Astrakhan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-balakovo",
        "keyword": "Buy Antminer Z15 Pro in Balakovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-barnaul",
        "keyword": "Buy Antminer Z15 Pro in Barnaul, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belgorod",
        "keyword": "Buy Antminer Z15 Pro in Belgorod, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-novorossiysk",
      "place": "Novorossiysk",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Novorossiysk, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-nizhny-tagil",
        "keyword": "Buy Antminer Z15 Pro in Nizhny Tagil, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-norilsk",
        "keyword": "Buy Antminer Z15 Pro in Norilsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-novokuznetsk",
        "keyword": "Buy Antminer Z15 Pro in Novokuznetsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-novosibirsk",
        "keyword": "Buy Antminer Z15 Pro in Novosibirsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-omsk",
        "keyword": "Buy Antminer Z15 Pro in Omsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-orenburg",
        "keyword": "Buy Antminer Z15 Pro in Orenburg, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-orsk",
        "keyword": "Buy Antminer Z15 Pro in Orsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-abakan",
        "keyword": "Buy Antminer Z15 Pro in Abakan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-achinsk",
        "keyword": "Buy Antminer Z15 Pro in Achinsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-anapa",
        "keyword": "Buy Antminer Z15 Pro in Anapa, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arkhangelsk",
        "keyword": "Buy Antminer Z15 Pro in Arkhangelsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-armavir",
        "keyword": "Buy Antminer Z15 Pro in Armavir, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-mons",
      "place": "Mons",
      "country": "Belgium",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Mons, Belgium"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-lokeren",
        "keyword": "Buy Antminer Z15 Pro in Lokeren, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mechelen",
        "keyword": "Buy Antminer Z15 Pro in Mechelen, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-menen",
        "keyword": "Buy Antminer Z15 Pro in Menen, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mouscron",
        "keyword": "Buy Antminer Z15 Pro in Mouscron, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-namur",
        "keyword": "Buy Antminer Z15 Pro in Namur, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ninove",
        "keyword": "Buy Antminer Z15 Pro in Ninove, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ostend",
        "keyword": "Buy Antminer Z15 Pro in Ostend, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kortrijk",
        "keyword": "Buy Antminer Z15 Pro in Kortrijk, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-la-louvière",
        "keyword": "Buy Antminer Z15 Pro in La Louvière, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leuven",
        "keyword": "Buy Antminer Z15 Pro in Leuven, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lier",
        "keyword": "Buy Antminer Z15 Pro in Lier, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-limbourg",
        "keyword": "Buy Antminer Z15 Pro in Limbourg, Belgium"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-mississippi",
      "place": "Mississippi",
      "country": "United States",
      "type": "state",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Mississippi"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-massachusetts",
        "keyword": "Buy Antminer Z15 Pro in Massachusetts"
      },
      {
        "slug": "buy-antminer-z15-pro-in-michigan",
        "keyword": "Buy Antminer Z15 Pro in Michigan"
      },
      {
        "slug": "buy-antminer-z15-pro-in-minnesota",
        "keyword": "Buy Antminer Z15 Pro in Minnesota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-missouri",
        "keyword": "Buy Antminer Z15 Pro in Missouri"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montana",
        "keyword": "Buy Antminer Z15 Pro in Montana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nebraska",
        "keyword": "Buy Antminer Z15 Pro in Nebraska"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nevada",
        "keyword": "Buy Antminer Z15 Pro in Nevada"
      },
      {
        "slug": "buy-asic-miner-in-mississippi",
        "keyword": "Buy ASIC Miner in Mississippi"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-mississippi",
        "keyword": "Buy Bitmain Antminer S23 in Mississippi"
      },
      {
        "slug": "buy-asic-miner-in-alaska",
        "keyword": "Buy ASIC Miner in Alaska"
      },
      {
        "slug": "buy-asic-miner-in-arizona",
        "keyword": "Buy ASIC Miner in Arizona"
      },
      {
        "slug": "buy-asic-miner-in-arkansas",
        "keyword": "Buy ASIC Miner in Arkansas"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-nebraska",
      "place": "Nebraska",
      "country": "United States",
      "type": "state",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Nebraska"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-mississippi",
        "keyword": "Buy Antminer Z15 Pro in Mississippi"
      },
      {
        "slug": "buy-antminer-z15-pro-in-missouri",
        "keyword": "Buy Antminer Z15 Pro in Missouri"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montana",
        "keyword": "Buy Antminer Z15 Pro in Montana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nevada",
        "keyword": "Buy Antminer Z15 Pro in Nevada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-hampshire",
        "keyword": "Buy Antminer Z15 Pro in New Hampshire"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-jersey",
        "keyword": "Buy Antminer Z15 Pro in New Jersey"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-mexico",
        "keyword": "Buy Antminer Z15 Pro in New Mexico"
      },
      {
        "slug": "buy-asic-miner-in-nebraska",
        "keyword": "Buy ASIC Miner in Nebraska"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nebraska",
        "keyword": "Buy Bitmain Antminer S23 in Nebraska"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-mississippi",
        "keyword": "Buy Bitmain Antminer S23 in Mississippi"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-missouri",
        "keyword": "Buy Bitmain Antminer S23 in Missouri"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-montana",
        "keyword": "Buy Bitmain Antminer S23 in Montana"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-brampton",
      "place": "Brampton",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Brampton, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-airdrie",
        "keyword": "Buy Antminer Z15 Pro in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-calgary",
        "keyword": "Buy Antminer Z15 Pro in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-edmonton",
        "keyword": "Buy Antminer Z15 Pro in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-grande-prairie",
        "keyword": "Buy Antminer Z15 Pro in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lethbridge",
        "keyword": "Buy Antminer Z15 Pro in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-medicine-hat",
        "keyword": "Buy Antminer Z15 Pro in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-brampton",
        "keyword": "Buy ASIC Miner in Brampton, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-brampton",
        "keyword": "Buy Bitmain Antminer S23 in Brampton, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brantford",
        "keyword": "Buy Antminer Z15 Pro in Brantford, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-burlington",
        "keyword": "Buy Antminer Z15 Pro in Burlington, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cambridge",
        "keyword": "Buy Antminer Z15 Pro in Cambridge, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-oshawa",
      "place": "Oshawa",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Oshawa, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-grande-prairie",
        "keyword": "Buy Antminer Z15 Pro in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lethbridge",
        "keyword": "Buy Antminer Z15 Pro in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-medicine-hat",
        "keyword": "Buy Antminer Z15 Pro in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-albert",
        "keyword": "Buy Antminer Z15 Pro in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-abbotsford",
        "keyword": "Buy Antminer Z15 Pro in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-burnaby",
        "keyword": "Buy Antminer Z15 Pro in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-oshawa",
        "keyword": "Buy ASIC Miner in Oshawa, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-oshawa",
        "keyword": "Buy Bitmain Antminer S23 in Oshawa, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-whitehorse",
        "keyword": "Buy Antminer Z15 Pro in Whitehorse, Yukon, Canada"
      },
      {
        "slug": "buy-asic-miner-in-airdrie",
        "keyword": "Buy ASIC Miner in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-calgary",
        "keyword": "Buy ASIC Miner in Calgary, Alberta, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-québec-city",
      "place": "Québec City",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Québec City, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-grande-prairie",
        "keyword": "Buy Antminer Z15 Pro in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lethbridge",
        "keyword": "Buy Antminer Z15 Pro in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-medicine-hat",
        "keyword": "Buy Antminer Z15 Pro in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-albert",
        "keyword": "Buy Antminer Z15 Pro in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-abbotsford",
        "keyword": "Buy Antminer Z15 Pro in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-burnaby",
        "keyword": "Buy Antminer Z15 Pro in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-québec-city",
        "keyword": "Buy ASIC Miner in Québec City, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-québec-city",
        "keyword": "Buy Bitmain Antminer S23 in Québec City, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-trois-rivières",
        "keyword": "Buy ASIC Miner in Trois-Rivières, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-moose-jaw",
        "keyword": "Buy ASIC Miner in Moose Jaw, Saskatchewan, Canada"
      },
      {
        "slug": "buy-asic-miner-in-prince-albert",
        "keyword": "Buy ASIC Miner in Prince Albert, Saskatchewan, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lancaster",
      "place": "Lancaster",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-gloucester",
        "keyword": "Buy Antminer Z15 Pro in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hereford",
        "keyword": "Buy Antminer Z15 Pro in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston-upon-hull",
        "keyword": "Buy Antminer Z15 Pro in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leeds",
        "keyword": "Buy Antminer Z15 Pro in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leicester",
        "keyword": "Buy Antminer Z15 Pro in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lichfield",
        "keyword": "Buy Antminer Z15 Pro in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lincoln",
        "keyword": "Buy Antminer Z15 Pro in Lincoln, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lancaster",
        "keyword": "Buy ASIC Miner in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lancaster",
        "keyword": "Buy Bitmain Antminer S23 in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-inverness",
        "keyword": "Buy Bitmain Antminer S23 in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-perth",
        "keyword": "Buy Bitmain Antminer S23 in Perth, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-stirling",
        "keyword": "Buy Bitmain Antminer S23 in Stirling, Scotland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-inverness",
      "place": "Inverness",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Inverness, Scotland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-exeter",
        "keyword": "Buy Antminer Z15 Pro in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gloucester",
        "keyword": "Buy Antminer Z15 Pro in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hereford",
        "keyword": "Buy Antminer Z15 Pro in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston-upon-hull",
        "keyword": "Buy Antminer Z15 Pro in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lancaster",
        "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leeds",
        "keyword": "Buy Antminer Z15 Pro in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leicester",
        "keyword": "Buy Antminer Z15 Pro in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-inverness",
        "keyword": "Buy ASIC Miner in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-inverness",
        "keyword": "Buy Bitmain Antminer S23 in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-bangor",
        "keyword": "Buy Bitmain Antminer S23 in Bangor, Wales, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-cardiff",
        "keyword": "Buy Bitmain Antminer S23 in Cardiff, Wales, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-newport",
        "keyword": "Buy Bitmain Antminer S23 in Newport, Wales, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-belfast",
      "place": "Belfast",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Belfast, Northern Ireland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-bath",
        "keyword": "Buy Antminer Z15 Pro in Bath, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-birmingham",
        "keyword": "Buy Antminer Z15 Pro in Birmingham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bradford",
        "keyword": "Buy Antminer Z15 Pro in Bradford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brighton-and-hove",
        "keyword": "Buy Antminer Z15 Pro in Brighton and Hove, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bristol",
        "keyword": "Buy Antminer Z15 Pro in Bristol, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-canterbury",
        "keyword": "Buy Antminer Z15 Pro in Canterbury, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-carlisle",
        "keyword": "Buy Antminer Z15 Pro in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-belfast",
        "keyword": "Buy ASIC Miner in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-belfast",
        "keyword": "Buy Bitmain Antminer S23 in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-edinburgh",
        "keyword": "Buy Antminer Z15 Pro in Edinburgh, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-glasgow",
        "keyword": "Buy Antminer Z15 Pro in Glasgow, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-inverness",
        "keyword": "Buy Antminer Z15 Pro in Inverness, Scotland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-indiana",
      "place": "Indiana",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Indiana"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-hawaii",
        "keyword": "Buy ASIC Miner in Hawaii"
      },
      {
        "slug": "buy-asic-miner-in-idaho",
        "keyword": "Buy ASIC Miner in Idaho"
      },
      {
        "slug": "buy-asic-miner-in-illinois",
        "keyword": "Buy ASIC Miner in Illinois"
      },
      {
        "slug": "buy-asic-miner-in-iowa",
        "keyword": "Buy ASIC Miner in Iowa"
      },
      {
        "slug": "buy-asic-miner-in-kansas",
        "keyword": "Buy ASIC Miner in Kansas"
      },
      {
        "slug": "buy-asic-miner-in-kentucky",
        "keyword": "Buy ASIC Miner in Kentucky"
      },
      {
        "slug": "buy-asic-miner-in-louisiana",
        "keyword": "Buy ASIC Miner in Louisiana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-indiana",
        "keyword": "Buy Antminer Z15 Pro in Indiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-indiana",
        "keyword": "Buy Bitmain Antminer S23 in Indiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kansas",
        "keyword": "Buy Bitmain Antminer S23 in Kansas"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kentucky",
        "keyword": "Buy Bitmain Antminer S23 in Kentucky"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-louisiana",
        "keyword": "Buy Bitmain Antminer S23 in Louisiana"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-pennsylvania",
      "place": "Pennsylvania",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Pennsylvania"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-ohio",
        "keyword": "Buy ASIC Miner in Ohio"
      },
      {
        "slug": "buy-asic-miner-in-oklahoma",
        "keyword": "Buy ASIC Miner in Oklahoma"
      },
      {
        "slug": "buy-asic-miner-in-oregon",
        "keyword": "Buy ASIC Miner in Oregon"
      },
      {
        "slug": "buy-asic-miner-in-rhode-island",
        "keyword": "Buy ASIC Miner in Rhode Island"
      },
      {
        "slug": "buy-asic-miner-in-south-carolina",
        "keyword": "Buy ASIC Miner in South Carolina"
      },
      {
        "slug": "buy-asic-miner-in-south-dakota",
        "keyword": "Buy ASIC Miner in South Dakota"
      },
      {
        "slug": "buy-asic-miner-in-tennessee",
        "keyword": "Buy ASIC Miner in Tennessee"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pennsylvania",
        "keyword": "Buy Antminer Z15 Pro in Pennsylvania"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-pennsylvania",
        "keyword": "Buy Bitmain Antminer S23 in Pennsylvania"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-mexico",
        "keyword": "Buy Antminer Z15 Pro in New Mexico"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-york",
        "keyword": "Buy Antminer Z15 Pro in New York"
      },
      {
        "slug": "buy-antminer-z15-pro-in-north-carolina",
        "keyword": "Buy Antminer Z15 Pro in North Carolina"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-wyoming",
      "place": "Wyoming",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Wyoming"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-washington",
        "keyword": "Buy ASIC Miner in Washington"
      },
      {
        "slug": "buy-asic-miner-in-west-virginia",
        "keyword": "Buy ASIC Miner in West Virginia"
      },
      {
        "slug": "buy-asic-miner-in-wisconsin",
        "keyword": "Buy ASIC Miner in Wisconsin"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wyoming",
        "keyword": "Buy Antminer Z15 Pro in Wyoming"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wyoming",
        "keyword": "Buy Bitmain Antminer S23 in Wyoming"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arizona",
        "keyword": "Buy Antminer Z15 Pro in Arizona"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arkansas",
        "keyword": "Buy Antminer Z15 Pro in Arkansas"
      },
      {
        "slug": "buy-antminer-z15-pro-in-california",
        "keyword": "Buy Antminer Z15 Pro in California"
      },
      {
        "slug": "buy-antminer-z15-pro-in-colorado",
        "keyword": "Buy Antminer Z15 Pro in Colorado"
      },
      {
        "slug": "buy-antminer-z15-pro-in-connecticut",
        "keyword": "Buy Antminer Z15 Pro in Connecticut"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delaware",
        "keyword": "Buy Antminer Z15 Pro in Delaware"
      },
      {
        "slug": "buy-antminer-z15-pro-in-florida",
        "keyword": "Buy Antminer Z15 Pro in Florida"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-langley",
      "place": "Langley",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Langley, British Columbia, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-calgary",
        "keyword": "Buy ASIC Miner in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-edmonton",
        "keyword": "Buy ASIC Miner in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-grande-prairie",
        "keyword": "Buy ASIC Miner in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-albert",
        "keyword": "Buy ASIC Miner in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-langley",
        "keyword": "Buy Antminer Z15 Pro in Langley, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-langley",
        "keyword": "Buy Bitmain Antminer S23 in Langley, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-trois-rivières",
        "keyword": "Buy Bitmain Antminer S23 in Trois-Rivières, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-moose-jaw",
        "keyword": "Buy Bitmain Antminer S23 in Moose Jaw, Saskatchewan, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-prince-albert",
        "keyword": "Buy Bitmain Antminer S23 in Prince Albert, Saskatchewan, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-ely",
      "place": "Ely",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Ely, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-derby",
        "keyword": "Buy ASIC Miner in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-doncaster",
        "keyword": "Buy ASIC Miner in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-durham",
        "keyword": "Buy ASIC Miner in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-exeter",
        "keyword": "Buy ASIC Miner in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-gloucester",
        "keyword": "Buy ASIC Miner in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-hereford",
        "keyword": "Buy ASIC Miner in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-kingston-upon-hull",
        "keyword": "Buy ASIC Miner in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ely",
        "keyword": "Buy Antminer Z15 Pro in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ely",
        "keyword": "Buy Bitmain Antminer S23 in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-glasgow",
        "keyword": "Buy ASIC Miner in Glasgow, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-inverness",
        "keyword": "Buy ASIC Miner in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-perth",
        "keyword": "Buy ASIC Miner in Perth, Scotland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-kingston-upon-hull",
      "place": "Kingston upon Hull",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Kingston upon Hull, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-exeter",
        "keyword": "Buy ASIC Miner in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-gloucester",
        "keyword": "Buy ASIC Miner in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-hereford",
        "keyword": "Buy ASIC Miner in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lancaster",
        "keyword": "Buy ASIC Miner in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leeds",
        "keyword": "Buy ASIC Miner in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leicester",
        "keyword": "Buy ASIC Miner in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lichfield",
        "keyword": "Buy ASIC Miner in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston-upon-hull",
        "keyword": "Buy Antminer Z15 Pro in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kingston-upon-hull",
        "keyword": "Buy Bitmain Antminer S23 in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-doncaster",
        "keyword": "Buy Bitmain Antminer S23 in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-durham",
        "keyword": "Buy Bitmain Antminer S23 in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ely",
        "keyword": "Buy Bitmain Antminer S23 in Ely, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-liverpool",
      "place": "Liverpool",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Liverpool, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-leicester",
        "keyword": "Buy ASIC Miner in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lichfield",
        "keyword": "Buy ASIC Miner in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lincoln",
        "keyword": "Buy ASIC Miner in Lincoln, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-manchester",
        "keyword": "Buy ASIC Miner in Manchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-milton-keynes",
        "keyword": "Buy ASIC Miner in Milton Keynes, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-newcastle-upon-tyne",
        "keyword": "Buy ASIC Miner in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-norwich",
        "keyword": "Buy ASIC Miner in Norwich, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-liverpool",
        "keyword": "Buy Antminer Z15 Pro in Liverpool, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-liverpool",
        "keyword": "Buy Bitmain Antminer S23 in Liverpool, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-newry",
        "keyword": "Buy Bitmain Antminer S23 in Newry, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bath",
        "keyword": "Buy Antminer Z15 Pro in Bath, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-birmingham",
        "keyword": "Buy Antminer Z15 Pro in Birmingham, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-plymouth",
      "place": "Plymouth",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Plymouth, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-norwich",
        "keyword": "Buy ASIC Miner in Norwich, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-nottingham",
        "keyword": "Buy ASIC Miner in Nottingham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-oxford",
        "keyword": "Buy ASIC Miner in Oxford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-portsmouth",
        "keyword": "Buy ASIC Miner in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-preston",
        "keyword": "Buy ASIC Miner in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-ripon",
        "keyword": "Buy ASIC Miner in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salford",
        "keyword": "Buy ASIC Miner in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-plymouth",
        "keyword": "Buy Antminer Z15 Pro in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-plymouth",
        "keyword": "Buy Bitmain Antminer S23 in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-liverpool",
        "keyword": "Buy Bitmain Antminer S23 in Liverpool, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-manchester",
        "keyword": "Buy Bitmain Antminer S23 in Manchester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-milton-keynes",
        "keyword": "Buy Bitmain Antminer S23 in Milton Keynes, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-salisbury",
      "place": "Salisbury",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Salisbury, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-preston",
        "keyword": "Buy ASIC Miner in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-ripon",
        "keyword": "Buy ASIC Miner in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salford",
        "keyword": "Buy ASIC Miner in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-sheffield",
        "keyword": "Buy ASIC Miner in Sheffield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southampton",
        "keyword": "Buy ASIC Miner in Southampton, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southend-on-sea",
        "keyword": "Buy ASIC Miner in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-st-albans",
        "keyword": "Buy ASIC Miner in St Albans, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salisbury",
        "keyword": "Buy Antminer Z15 Pro in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-salisbury",
        "keyword": "Buy Bitmain Antminer S23 in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-nottingham",
        "keyword": "Buy ASIC Miner in Nottingham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-oxford",
        "keyword": "Buy ASIC Miner in Oxford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-plymouth",
        "keyword": "Buy ASIC Miner in Plymouth, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-worcester",
      "place": "Worcester",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Worcester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-westminster",
        "keyword": "Buy ASIC Miner in Westminster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-winchester",
        "keyword": "Buy ASIC Miner in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-wolverhampton",
        "keyword": "Buy ASIC Miner in Wolverhampton, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-york",
        "keyword": "Buy ASIC Miner in York, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-aberdeen",
        "keyword": "Buy ASIC Miner in Aberdeen, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-dundee",
        "keyword": "Buy ASIC Miner in Dundee, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-dunfermline",
        "keyword": "Buy ASIC Miner in Dunfermline, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-worcester",
        "keyword": "Buy Antminer Z15 Pro in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-worcester",
        "keyword": "Buy Bitmain Antminer S23 in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-stoke-on-trent",
        "keyword": "Buy Bitmain Antminer S23 in Stoke-on-Trent, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-sunderland",
        "keyword": "Buy Bitmain Antminer S23 in Sunderland, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wakefield",
        "keyword": "Buy Bitmain Antminer S23 in Wakefield, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-indiana",
      "place": "Indiana",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Indiana"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-hawaii",
        "keyword": "Buy Bitmain Antminer S23 in Hawaii"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-idaho",
        "keyword": "Buy Bitmain Antminer S23 in Idaho"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-illinois",
        "keyword": "Buy Bitmain Antminer S23 in Illinois"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-iowa",
        "keyword": "Buy Bitmain Antminer S23 in Iowa"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kansas",
        "keyword": "Buy Bitmain Antminer S23 in Kansas"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kentucky",
        "keyword": "Buy Bitmain Antminer S23 in Kentucky"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-louisiana",
        "keyword": "Buy Bitmain Antminer S23 in Louisiana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-indiana",
        "keyword": "Buy Antminer Z15 Pro in Indiana"
      },
      {
        "slug": "buy-asic-miner-in-indiana",
        "keyword": "Buy ASIC Miner in Indiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-oregon",
        "keyword": "Buy Bitmain Antminer S23 in Oregon"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-pennsylvania",
        "keyword": "Buy Bitmain Antminer S23 in Pennsylvania"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-rhode-island",
        "keyword": "Buy Bitmain Antminer S23 in Rhode Island"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-wyoming",
      "place": "Wyoming",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Wyoming"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-washington",
        "keyword": "Buy Bitmain Antminer S23 in Washington"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-west-virginia",
        "keyword": "Buy Bitmain Antminer S23 in West Virginia"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wisconsin",
        "keyword": "Buy Bitmain Antminer S23 in Wisconsin"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wyoming",
        "keyword": "Buy Antminer Z15 Pro in Wyoming"
      },
      {
        "slug": "buy-asic-miner-in-wyoming",
        "keyword": "Buy ASIC Miner in Wyoming"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mississippi",
        "keyword": "Buy Antminer Z15 Pro in Mississippi"
      },
      {
        "slug": "buy-antminer-z15-pro-in-missouri",
        "keyword": "Buy Antminer Z15 Pro in Missouri"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montana",
        "keyword": "Buy Antminer Z15 Pro in Montana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nebraska",
        "keyword": "Buy Antminer Z15 Pro in Nebraska"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nevada",
        "keyword": "Buy Antminer Z15 Pro in Nevada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-hampshire",
        "keyword": "Buy Antminer Z15 Pro in New Hampshire"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-jersey",
        "keyword": "Buy Antminer Z15 Pro in New Jersey"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-langley",
      "place": "Langley",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Langley, British Columbia, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-calgary",
        "keyword": "Buy Bitmain Antminer S23 in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-edmonton",
        "keyword": "Buy Bitmain Antminer S23 in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-langley",
        "keyword": "Buy Antminer Z15 Pro in Langley, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-langley",
        "keyword": "Buy ASIC Miner in Langley, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-whitby",
        "keyword": "Buy Bitmain Antminer S23 in Whitby, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-windsor",
        "keyword": "Buy Bitmain Antminer S23 in Windsor, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-charlottetown",
        "keyword": "Buy Bitmain Antminer S23 in Charlottetown, Prince Edward Island, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-niagara-falls",
      "place": "Niagara Falls",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Niagara Falls, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-niagara-falls",
        "keyword": "Buy Antminer Z15 Pro in Niagara Falls, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-niagara-falls",
        "keyword": "Buy ASIC Miner in Niagara Falls, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-summerside",
        "keyword": "Buy ASIC Miner in Summerside, Prince Edward Island, Canada"
      },
      {
        "slug": "buy-asic-miner-in-gatineau",
        "keyword": "Buy ASIC Miner in Gatineau, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-laval",
        "keyword": "Buy ASIC Miner in Laval, Quebec, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-chichester",
      "place": "Chichester",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Chichester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-carlisle",
        "keyword": "Buy Bitmain Antminer S23 in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chelmsford",
        "keyword": "Buy Bitmain Antminer S23 in Chelmsford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chester",
        "keyword": "Buy Bitmain Antminer S23 in Chester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-colchester",
        "keyword": "Buy Bitmain Antminer S23 in Colchester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-coventry",
        "keyword": "Buy Bitmain Antminer S23 in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-derby",
        "keyword": "Buy Bitmain Antminer S23 in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-doncaster",
        "keyword": "Buy Bitmain Antminer S23 in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chichester",
        "keyword": "Buy Antminer Z15 Pro in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chichester",
        "keyword": "Buy ASIC Miner in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cardiff",
        "keyword": "Buy Antminer Z15 Pro in Cardiff, Wales, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newport",
        "keyword": "Buy Antminer Z15 Pro in Newport, Wales, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-asaph",
        "keyword": "Buy Antminer Z15 Pro in St Asaph, Wales, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-salisbury",
      "place": "Salisbury",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Salisbury, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-preston",
        "keyword": "Buy Bitmain Antminer S23 in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ripon",
        "keyword": "Buy Bitmain Antminer S23 in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-salford",
        "keyword": "Buy Bitmain Antminer S23 in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-sheffield",
        "keyword": "Buy Bitmain Antminer S23 in Sheffield, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-southampton",
        "keyword": "Buy Bitmain Antminer S23 in Southampton, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-southend-on-sea",
        "keyword": "Buy Bitmain Antminer S23 in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albans",
        "keyword": "Buy Bitmain Antminer S23 in St Albans, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salisbury",
        "keyword": "Buy Antminer Z15 Pro in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salisbury",
        "keyword": "Buy ASIC Miner in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-newport",
        "keyword": "Buy ASIC Miner in Newport, Wales, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-st-asaph",
        "keyword": "Buy ASIC Miner in St Asaph, Wales, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-st-davids",
        "keyword": "Buy ASIC Miner in St Davids, Wales, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-winchester",
      "place": "Winchester",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Winchester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-wakefield",
        "keyword": "Buy Bitmain Antminer S23 in Wakefield, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wells",
        "keyword": "Buy Bitmain Antminer S23 in Wells, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-westminster",
        "keyword": "Buy Bitmain Antminer S23 in Westminster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wolverhampton",
        "keyword": "Buy Bitmain Antminer S23 in Wolverhampton, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-worcester",
        "keyword": "Buy Bitmain Antminer S23 in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-york",
        "keyword": "Buy Bitmain Antminer S23 in York, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-aberdeen",
        "keyword": "Buy Bitmain Antminer S23 in Aberdeen, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-winchester",
        "keyword": "Buy Antminer Z15 Pro in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-winchester",
        "keyword": "Buy ASIC Miner in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southend-on-sea",
        "keyword": "Buy ASIC Miner in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-st-albans",
        "keyword": "Buy ASIC Miner in St Albans, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-stoke-on-trent",
        "keyword": "Buy ASIC Miner in Stoke-on-Trent, England, United Kingdom"
      }
    ]
  }
];
