// AUTO-GENERATED by scripts/build-marketplace-shards.ts — do not edit.
import type { LocationEntry } from "./types";

export const ENTRIES: LocationEntry[] = [
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-den-helder",
      "place": "Den Helder",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Den Helder, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-breda",
        "keyword": "Buy Antminer Z15 Pro in Breda, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delft",
        "keyword": "Buy Antminer Z15 Pro in Delft, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-den-bosch",
        "keyword": "Buy Antminer Z15 Pro in Den Bosch, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-deventer",
        "keyword": "Buy Antminer Z15 Pro in Deventer, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dordrecht",
        "keyword": "Buy Antminer Z15 Pro in Dordrecht, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ede",
        "keyword": "Buy Antminer Z15 Pro in Ede, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-eindhoven",
        "keyword": "Buy Antminer Z15 Pro in Eindhoven, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hoorn",
        "keyword": "Buy Antminer Z15 Pro in Hoorn, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leeuwarden",
        "keyword": "Buy Antminer Z15 Pro in Leeuwarden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leiden",
        "keyword": "Buy Antminer Z15 Pro in Leiden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lelystad",
        "keyword": "Buy Antminer Z15 Pro in Lelystad, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-maastricht",
        "keyword": "Buy Antminer Z15 Pro in Maastricht, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lelystad",
      "place": "Lelystad",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lelystad, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-hoorn",
        "keyword": "Buy Antminer Z15 Pro in Hoorn, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leeuwarden",
        "keyword": "Buy Antminer Z15 Pro in Leeuwarden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leiden",
        "keyword": "Buy Antminer Z15 Pro in Leiden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-maastricht",
        "keyword": "Buy Antminer Z15 Pro in Maastricht, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-middelburg",
        "keyword": "Buy Antminer Z15 Pro in Middelburg, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nijmegen",
        "keyword": "Buy Antminer Z15 Pro in Nijmegen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oosterhout",
        "keyword": "Buy Antminer Z15 Pro in Oosterhout, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zwolle",
        "keyword": "Buy Antminer Z15 Pro in Zwolle, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-alkmaar",
        "keyword": "Buy Antminer Z15 Pro in Alkmaar, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-almelo",
        "keyword": "Buy Antminer Z15 Pro in Almelo, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-almere",
        "keyword": "Buy Antminer Z15 Pro in Almere, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-amersfoort",
        "keyword": "Buy Antminer Z15 Pro in Amersfoort, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-maastricht",
      "place": "Maastricht",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Maastricht, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-leeuwarden",
        "keyword": "Buy Antminer Z15 Pro in Leeuwarden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leiden",
        "keyword": "Buy Antminer Z15 Pro in Leiden, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lelystad",
        "keyword": "Buy Antminer Z15 Pro in Lelystad, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-middelburg",
        "keyword": "Buy Antminer Z15 Pro in Middelburg, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nijmegen",
        "keyword": "Buy Antminer Z15 Pro in Nijmegen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oosterhout",
        "keyword": "Buy Antminer Z15 Pro in Oosterhout, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oss",
        "keyword": "Buy Antminer Z15 Pro in Oss, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sittard",
        "keyword": "Buy Antminer Z15 Pro in Sittard, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-spijkenisse",
        "keyword": "Buy Antminer Z15 Pro in Spijkenisse, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tilburg",
        "keyword": "Buy Antminer Z15 Pro in Tilburg, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-utrecht",
        "keyword": "Buy Antminer Z15 Pro in Utrecht, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-veenendaal",
        "keyword": "Buy Antminer Z15 Pro in Veenendaal, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-roosendaal",
      "place": "Roosendaal",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Roosendaal, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-nijmegen",
        "keyword": "Buy Antminer Z15 Pro in Nijmegen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oosterhout",
        "keyword": "Buy Antminer Z15 Pro in Oosterhout, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oss",
        "keyword": "Buy Antminer Z15 Pro in Oss, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rotterdam",
        "keyword": "Buy Antminer Z15 Pro in Rotterdam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schiedam",
        "keyword": "Buy Antminer Z15 Pro in Schiedam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sittard",
        "keyword": "Buy Antminer Z15 Pro in Sittard, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-spijkenisse",
        "keyword": "Buy Antminer Z15 Pro in Spijkenisse, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wageningen",
        "keyword": "Buy Antminer Z15 Pro in Wageningen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-weert",
        "keyword": "Buy Antminer Z15 Pro in Weert, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zaandam",
        "keyword": "Buy Antminer Z15 Pro in Zaandam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zoetermeer",
        "keyword": "Buy Antminer Z15 Pro in Zoetermeer, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zwolle",
        "keyword": "Buy Antminer Z15 Pro in Zwolle, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-esslingen-am-neckar",
      "place": "Esslingen am Neckar",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Esslingen am Neckar, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-erfurt",
        "keyword": "Buy Antminer Z15 Pro in Erfurt, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-erlangen",
        "keyword": "Buy Antminer Z15 Pro in Erlangen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-essen",
        "keyword": "Buy Antminer Z15 Pro in Essen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-flensburg",
        "keyword": "Buy Antminer Z15 Pro in Flensburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-frankfurt-am-main",
        "keyword": "Buy Antminer Z15 Pro in Frankfurt am Main, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-freiburg-im-breisgau",
        "keyword": "Buy Antminer Z15 Pro in Freiburg im Breisgau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-friedrichshafen",
        "keyword": "Buy Antminer Z15 Pro in Friedrichshafen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dortmund",
        "keyword": "Buy Antminer Z15 Pro in Dortmund, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dresden",
        "keyword": "Buy Antminer Z15 Pro in Dresden, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-duisburg",
        "keyword": "Buy Antminer Z15 Pro in Duisburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-düren",
        "keyword": "Buy Antminer Z15 Pro in Düren, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-düsseldorf",
        "keyword": "Buy Antminer Z15 Pro in Düsseldorf, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-konstanz",
      "place": "Konstanz",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Konstanz, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-kempten",
        "keyword": "Buy Antminer Z15 Pro in Kempten, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kiel",
        "keyword": "Buy Antminer Z15 Pro in Kiel, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-koblenz",
        "keyword": "Buy Antminer Z15 Pro in Koblenz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krefeld",
        "keyword": "Buy Antminer Z15 Pro in Krefeld, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-landshut",
        "keyword": "Buy Antminer Z15 Pro in Landshut, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leipzig",
        "keyword": "Buy Antminer Z15 Pro in Leipzig, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leverkusen",
        "keyword": "Buy Antminer Z15 Pro in Leverkusen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-darmstadt",
        "keyword": "Buy Antminer Z15 Pro in Darmstadt, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delmenhorst",
        "keyword": "Buy Antminer Z15 Pro in Delmenhorst, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dessau-roßlau",
        "keyword": "Buy Antminer Z15 Pro in Dessau-Roßlau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dortmund",
        "keyword": "Buy Antminer Z15 Pro in Dortmund, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dresden",
        "keyword": "Buy Antminer Z15 Pro in Dresden, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-stuttgart",
      "place": "Stuttgart",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Stuttgart, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-siegen",
        "keyword": "Buy Antminer Z15 Pro in Siegen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-solingen",
        "keyword": "Buy Antminer Z15 Pro in Solingen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-speyer",
        "keyword": "Buy Antminer Z15 Pro in Speyer, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-trier",
        "keyword": "Buy Antminer Z15 Pro in Trier, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ulm",
        "keyword": "Buy Antminer Z15 Pro in Ulm, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-villingen-schwenningen",
        "keyword": "Buy Antminer Z15 Pro in Villingen-Schwenningen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-weimar",
        "keyword": "Buy Antminer Z15 Pro in Weimar, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hanau",
        "keyword": "Buy Antminer Z15 Pro in Hanau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hannover",
        "keyword": "Buy Antminer Z15 Pro in Hannover, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-heidelberg",
        "keyword": "Buy Antminer Z15 Pro in Heidelberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-heilbronn",
        "keyword": "Buy Antminer Z15 Pro in Heilbronn, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-herne",
        "keyword": "Buy Antminer Z15 Pro in Herne, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-villingen-schwenningen",
      "place": "Villingen-Schwenningen",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Villingen-Schwenningen, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-stuttgart",
        "keyword": "Buy Antminer Z15 Pro in Stuttgart, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-trier",
        "keyword": "Buy Antminer Z15 Pro in Trier, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ulm",
        "keyword": "Buy Antminer Z15 Pro in Ulm, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-weimar",
        "keyword": "Buy Antminer Z15 Pro in Weimar, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wiesbaden",
        "keyword": "Buy Antminer Z15 Pro in Wiesbaden, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wilhelmshaven",
        "keyword": "Buy Antminer Z15 Pro in Wilhelmshaven, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-witten",
        "keyword": "Buy Antminer Z15 Pro in Witten, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bergisch-gladbach",
        "keyword": "Buy Antminer Z15 Pro in Bergisch Gladbach, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-berlin",
        "keyword": "Buy Antminer Z15 Pro in Berlin, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bielefeld",
        "keyword": "Buy Antminer Z15 Pro in Bielefeld, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bochum",
        "keyword": "Buy Antminer Z15 Pro in Bochum, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bonn",
        "keyword": "Buy Antminer Z15 Pro in Bonn, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-zwickau",
      "place": "Zwickau",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Zwickau, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-worms",
        "keyword": "Buy Antminer Z15 Pro in Worms, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wuppertal",
        "keyword": "Buy Antminer Z15 Pro in Wuppertal, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-würzburg",
        "keyword": "Buy Antminer Z15 Pro in Würzburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bremerhaven",
        "keyword": "Buy Antminer Z15 Pro in Bremerhaven, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chemnitz",
        "keyword": "Buy Antminer Z15 Pro in Chemnitz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cottbus",
        "keyword": "Buy Antminer Z15 Pro in Cottbus, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cuxhaven",
        "keyword": "Buy Antminer Z15 Pro in Cuxhaven, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-darmstadt",
        "keyword": "Buy Antminer Z15 Pro in Darmstadt, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delmenhorst",
        "keyword": "Buy Antminer Z15 Pro in Delmenhorst, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dessau-roßlau",
        "keyword": "Buy Antminer Z15 Pro in Dessau-Roßlau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dortmund",
        "keyword": "Buy Antminer Z15 Pro in Dortmund, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dresden",
        "keyword": "Buy Antminer Z15 Pro in Dresden, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-klosterneuburg",
      "place": "Klosterneuburg",
      "country": "Austria",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Klosterneuburg, Austria"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-innsbruck",
        "keyword": "Buy Antminer Z15 Pro in Innsbruck, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kapfenberg",
        "keyword": "Buy Antminer Z15 Pro in Kapfenberg, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-klagenfurt",
        "keyword": "Buy Antminer Z15 Pro in Klagenfurt, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krems-an-der-donau",
        "keyword": "Buy Antminer Z15 Pro in Krems an der Donau, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kufstein",
        "keyword": "Buy Antminer Z15 Pro in Kufstein, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leoben",
        "keyword": "Buy Antminer Z15 Pro in Leoben, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-leonding",
        "keyword": "Buy Antminer Z15 Pro in Leonding, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-steyr",
        "keyword": "Buy Antminer Z15 Pro in Steyr, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ternitz",
        "keyword": "Buy Antminer Z15 Pro in Ternitz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traiskirchen",
        "keyword": "Buy Antminer Z15 Pro in Traiskirchen, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traun",
        "keyword": "Buy Antminer Z15 Pro in Traun, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vienna",
        "keyword": "Buy Antminer Z15 Pro in Vienna, Austria"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-bendigo",
      "place": "Bendigo",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Bendigo, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-albury",
        "keyword": "Buy Antminer Z15 Pro in Albury, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-alice-springs",
        "keyword": "Buy Antminer Z15 Pro in Alice Springs, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ballarat",
        "keyword": "Buy Antminer Z15 Pro in Ballarat, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-berri",
        "keyword": "Buy Antminer Z15 Pro in Berri, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brisbane",
        "keyword": "Buy Antminer Z15 Pro in Brisbane, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bunbury",
        "keyword": "Buy Antminer Z15 Pro in Bunbury, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bundaberg",
        "keyword": "Buy Antminer Z15 Pro in Bundaberg, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dubbo",
        "keyword": "Buy Antminer Z15 Pro in Dubbo, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-echuca",
        "keyword": "Buy Antminer Z15 Pro in Echuca, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-forster",
        "keyword": "Buy Antminer Z15 Pro in Forster, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-geelong",
        "keyword": "Buy Antminer Z15 Pro in Geelong, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-geraldton",
        "keyword": "Buy Antminer Z15 Pro in Geraldton, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-karratha",
      "place": "Karratha",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Karratha, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-hervey-bay",
        "keyword": "Buy Antminer Z15 Pro in Hervey Bay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hobart",
        "keyword": "Buy Antminer Z15 Pro in Hobart, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kalgoorlie",
        "keyword": "Buy Antminer Z15 Pro in Kalgoorlie, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-launceston",
        "keyword": "Buy Antminer Z15 Pro in Launceston, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mackay",
        "keyword": "Buy Antminer Z15 Pro in Mackay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mandurah",
        "keyword": "Buy Antminer Z15 Pro in Mandurah, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-melbourne",
        "keyword": "Buy Antminer Z15 Pro in Melbourne, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mildura",
        "keyword": "Buy Antminer Z15 Pro in Mildura, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mount-gambier",
        "keyword": "Buy Antminer Z15 Pro in Mount Gambier, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newcastle",
        "keyword": "Buy Antminer Z15 Pro in Newcastle, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nowra",
        "keyword": "Buy Antminer Z15 Pro in Nowra, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-orange",
        "keyword": "Buy Antminer Z15 Pro in Orange, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-shepparton",
      "place": "Shepparton",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Shepparton, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-port-hedland",
        "keyword": "Buy Antminer Z15 Pro in Port Hedland, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-macquarie",
        "keyword": "Buy Antminer Z15 Pro in Port Macquarie, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rockhampton",
        "keyword": "Buy Antminer Z15 Pro in Rockhampton, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sunshine-coast",
        "keyword": "Buy Antminer Z15 Pro in Sunshine Coast, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-swan-hill",
        "keyword": "Buy Antminer Z15 Pro in Swan Hill, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sydney",
        "keyword": "Buy Antminer Z15 Pro in Sydney, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tamworth",
        "keyword": "Buy Antminer Z15 Pro in Tamworth, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-goulburn",
        "keyword": "Buy Antminer Z15 Pro in Goulburn, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hervey-bay",
        "keyword": "Buy Antminer Z15 Pro in Hervey Bay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hobart",
        "keyword": "Buy Antminer Z15 Pro in Hobart, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kalgoorlie",
        "keyword": "Buy Antminer Z15 Pro in Kalgoorlie, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-karratha",
        "keyword": "Buy Antminer Z15 Pro in Karratha, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-whyalla",
      "place": "Whyalla",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Whyalla, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-traralgon",
        "keyword": "Buy Antminer Z15 Pro in Traralgon, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wagga-wagga",
        "keyword": "Buy Antminer Z15 Pro in Wagga Wagga, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-warrnambool",
        "keyword": "Buy Antminer Z15 Pro in Warrnambool, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wollongong",
        "keyword": "Buy Antminer Z15 Pro in Wollongong, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newcastle",
        "keyword": "Buy Antminer Z15 Pro in Newcastle, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nowra",
        "keyword": "Buy Antminer Z15 Pro in Nowra, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-orange",
        "keyword": "Buy Antminer Z15 Pro in Orange, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-perth",
        "keyword": "Buy Antminer Z15 Pro in Perth, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-augusta",
        "keyword": "Buy Antminer Z15 Pro in Port Augusta, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-hedland",
        "keyword": "Buy Antminer Z15 Pro in Port Hedland, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-macquarie",
        "keyword": "Buy Antminer Z15 Pro in Port Macquarie, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rockhampton",
        "keyword": "Buy Antminer Z15 Pro in Rockhampton, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-wiltz",
      "place": "Wiltz",
      "country": "Luxembourg",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Wiltz, Luxembourg"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-steinfort",
        "keyword": "Buy Antminer Z15 Pro in Steinfort, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-strassen",
        "keyword": "Buy Antminer Z15 Pro in Strassen, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vianden",
        "keyword": "Buy Antminer Z15 Pro in Vianden, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bettembourg",
        "keyword": "Buy Antminer Z15 Pro in Bettembourg, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-clervaux",
        "keyword": "Buy Antminer Z15 Pro in Clervaux, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dudelange",
        "keyword": "Buy Antminer Z15 Pro in Dudelange, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-echternach",
        "keyword": "Buy Antminer Z15 Pro in Echternach, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-esch-sur-alzette",
        "keyword": "Buy Antminer Z15 Pro in Esch-sur-Alzette, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ettelbruck",
        "keyword": "Buy Antminer Z15 Pro in Ettelbruck, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-grevenmacher",
        "keyword": "Buy Antminer Z15 Pro in Grevenmacher, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-junglinster",
        "keyword": "Buy Antminer Z15 Pro in Junglinster, Luxembourg"
      },
      {
        "slug": "buy-antminer-z15-pro-in-luxembourg-city",
        "keyword": "Buy Antminer Z15 Pro in Luxembourg City, Luxembourg"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-mykolaiv",
      "place": "Mykolaiv",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Mykolaiv, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-mariupol",
        "keyword": "Buy Antminer Z15 Pro in Mariupol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-melitopol",
        "keyword": "Buy Antminer Z15 Pro in Melitopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mukachevo",
        "keyword": "Buy Antminer Z15 Pro in Mukachevo, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nizhyn",
        "keyword": "Buy Antminer Z15 Pro in Nizhyn, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-odesa",
        "keyword": "Buy Antminer Z15 Pro in Odesa, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pavlohrad",
        "keyword": "Buy Antminer Z15 Pro in Pavlohrad, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-poltava",
        "keyword": "Buy Antminer Z15 Pro in Poltava, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zhytomyr",
        "keyword": "Buy Antminer Z15 Pro in Zhytomyr, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-alchevsk",
        "keyword": "Buy Antminer Z15 Pro in Alchevsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bakhmut",
        "keyword": "Buy Antminer Z15 Pro in Bakhmut, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-balakliia",
        "keyword": "Buy Antminer Z15 Pro in Balakliia, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-berdychiv",
        "keyword": "Buy Antminer Z15 Pro in Berdychiv, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-izhevsk",
      "place": "Izhevsk",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Izhevsk, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-grozny",
        "keyword": "Buy Antminer Z15 Pro in Grozny, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-irkutsk",
        "keyword": "Buy Antminer Z15 Pro in Irkutsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ivanovo",
        "keyword": "Buy Antminer Z15 Pro in Ivanovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kaliningrad",
        "keyword": "Buy Antminer Z15 Pro in Kaliningrad, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kaluga",
        "keyword": "Buy Antminer Z15 Pro in Kaluga, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kazan",
        "keyword": "Buy Antminer Z15 Pro in Kazan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kemerovo",
        "keyword": "Buy Antminer Z15 Pro in Kemerovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bratsk",
        "keyword": "Buy Antminer Z15 Pro in Bratsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bryansk",
        "keyword": "Buy Antminer Z15 Pro in Bryansk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cheboksary",
        "keyword": "Buy Antminer Z15 Pro in Cheboksary, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chelyabinsk",
        "keyword": "Buy Antminer Z15 Pro in Chelyabinsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-cherepovets",
        "keyword": "Buy Antminer Z15 Pro in Cherepovets, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-moscow",
      "place": "Moscow",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Moscow, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-magnitogorsk",
        "keyword": "Buy Antminer Z15 Pro in Magnitogorsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-makhachkala",
        "keyword": "Buy Antminer Z15 Pro in Makhachkala, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-maykop",
        "keyword": "Buy Antminer Z15 Pro in Maykop, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-murmansk",
        "keyword": "Buy Antminer Z15 Pro in Murmansk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mytishchi",
        "keyword": "Buy Antminer Z15 Pro in Mytishchi, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-naberezhnye-chelny",
        "keyword": "Buy Antminer Z15 Pro in Naberezhnye Chelny, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nakhodka",
        "keyword": "Buy Antminer Z15 Pro in Nakhodka, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-balakovo",
        "keyword": "Buy Antminer Z15 Pro in Balakovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-barnaul",
        "keyword": "Buy Antminer Z15 Pro in Barnaul, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belgorod",
        "keyword": "Buy Antminer Z15 Pro in Belgorod, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-biysk",
        "keyword": "Buy Antminer Z15 Pro in Biysk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-blagoveshchensk",
        "keyword": "Buy Antminer Z15 Pro in Blagoveshchensk, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-sochi",
      "place": "Sochi",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Sochi, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-saratov",
        "keyword": "Buy Antminer Z15 Pro in Saratov, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shakhty",
        "keyword": "Buy Antminer Z15 Pro in Shakhty, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-smolensk",
        "keyword": "Buy Antminer Z15 Pro in Smolensk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-petersburg",
        "keyword": "Buy Antminer Z15 Pro in St Petersburg, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-stavropol",
        "keyword": "Buy Antminer Z15 Pro in Stavropol, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sterlitamak",
        "keyword": "Buy Antminer Z15 Pro in Sterlitamak, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-surgut",
        "keyword": "Buy Antminer Z15 Pro in Surgut, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lipetsk",
        "keyword": "Buy Antminer Z15 Pro in Lipetsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lyubertsy",
        "keyword": "Buy Antminer Z15 Pro in Lyubertsy, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-magadan",
        "keyword": "Buy Antminer Z15 Pro in Magadan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-magnitogorsk",
        "keyword": "Buy Antminer Z15 Pro in Magnitogorsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-makhachkala",
        "keyword": "Buy Antminer Z15 Pro in Makhachkala, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-syktyvkar",
      "place": "Syktyvkar",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Syktyvkar, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-stavropol",
        "keyword": "Buy Antminer Z15 Pro in Stavropol, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sterlitamak",
        "keyword": "Buy Antminer Z15 Pro in Sterlitamak, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-surgut",
        "keyword": "Buy Antminer Z15 Pro in Surgut, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tambov",
        "keyword": "Buy Antminer Z15 Pro in Tambov, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tolyatti",
        "keyword": "Buy Antminer Z15 Pro in Tolyatti, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tomsk",
        "keyword": "Buy Antminer Z15 Pro in Tomsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tula",
        "keyword": "Buy Antminer Z15 Pro in Tula, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krasnodar",
        "keyword": "Buy Antminer Z15 Pro in Krasnodar, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-krasnoyarsk",
        "keyword": "Buy Antminer Z15 Pro in Krasnoyarsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kurgan",
        "keyword": "Buy Antminer Z15 Pro in Kurgan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kursk",
        "keyword": "Buy Antminer Z15 Pro in Kursk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyzyl",
        "keyword": "Buy Antminer Z15 Pro in Kyzyl, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-dartmouth",
      "place": "Dartmouth",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Dartmouth, Nova Scotia, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-airdrie",
        "keyword": "Buy Antminer Z15 Pro in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-calgary",
        "keyword": "Buy Antminer Z15 Pro in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-edmonton",
        "keyword": "Buy Antminer Z15 Pro in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-grande-prairie",
        "keyword": "Buy Antminer Z15 Pro in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lethbridge",
        "keyword": "Buy Antminer Z15 Pro in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-medicine-hat",
        "keyword": "Buy Antminer Z15 Pro in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-dartmouth",
        "keyword": "Buy ASIC Miner in Dartmouth, Nova Scotia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-dartmouth",
        "keyword": "Buy Bitmain Antminer S23 in Dartmouth, Nova Scotia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lévis",
        "keyword": "Buy Bitmain Antminer S23 in Lévis, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-montréal",
        "keyword": "Buy Bitmain Antminer S23 in Montréal, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-québec-city",
        "keyword": "Buy Bitmain Antminer S23 in Québec City, Quebec, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-chichester",
      "place": "Chichester",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Chichester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-carlisle",
        "keyword": "Buy Antminer Z15 Pro in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chelmsford",
        "keyword": "Buy Antminer Z15 Pro in Chelmsford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chester",
        "keyword": "Buy Antminer Z15 Pro in Chester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-colchester",
        "keyword": "Buy Antminer Z15 Pro in Colchester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-coventry",
        "keyword": "Buy Antminer Z15 Pro in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-derby",
        "keyword": "Buy Antminer Z15 Pro in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-doncaster",
        "keyword": "Buy Antminer Z15 Pro in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chichester",
        "keyword": "Buy ASIC Miner in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chichester",
        "keyword": "Buy Bitmain Antminer S23 in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-newcastle-upon-tyne",
        "keyword": "Buy ASIC Miner in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-norwich",
        "keyword": "Buy ASIC Miner in Norwich, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-nottingham",
        "keyword": "Buy ASIC Miner in Nottingham, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-derby",
      "place": "Derby",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Derby, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-chichester",
        "keyword": "Buy Antminer Z15 Pro in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-colchester",
        "keyword": "Buy Antminer Z15 Pro in Colchester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-coventry",
        "keyword": "Buy Antminer Z15 Pro in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-doncaster",
        "keyword": "Buy Antminer Z15 Pro in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-durham",
        "keyword": "Buy Antminer Z15 Pro in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ely",
        "keyword": "Buy Antminer Z15 Pro in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-exeter",
        "keyword": "Buy Antminer Z15 Pro in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-derby",
        "keyword": "Buy ASIC Miner in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-derby",
        "keyword": "Buy Bitmain Antminer S23 in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-plymouth",
        "keyword": "Buy ASIC Miner in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-portsmouth",
        "keyword": "Buy ASIC Miner in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-preston",
        "keyword": "Buy ASIC Miner in Preston, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-ripon",
      "place": "Ripon",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Ripon, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-plymouth",
        "keyword": "Buy Antminer Z15 Pro in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-portsmouth",
        "keyword": "Buy Antminer Z15 Pro in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-preston",
        "keyword": "Buy Antminer Z15 Pro in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salford",
        "keyword": "Buy Antminer Z15 Pro in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salisbury",
        "keyword": "Buy Antminer Z15 Pro in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sheffield",
        "keyword": "Buy Antminer Z15 Pro in Sheffield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-southampton",
        "keyword": "Buy Antminer Z15 Pro in Southampton, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-ripon",
        "keyword": "Buy ASIC Miner in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ripon",
        "keyword": "Buy Bitmain Antminer S23 in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bath",
        "keyword": "Buy Antminer Z15 Pro in Bath, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-birmingham",
        "keyword": "Buy Antminer Z15 Pro in Birmingham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bradford",
        "keyword": "Buy Antminer Z15 Pro in Bradford, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-southend-on-sea",
      "place": "Southend-on-Sea",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Southend-on-Sea, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-salisbury",
        "keyword": "Buy Antminer Z15 Pro in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sheffield",
        "keyword": "Buy Antminer Z15 Pro in Sheffield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-southampton",
        "keyword": "Buy Antminer Z15 Pro in Southampton, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-albans",
        "keyword": "Buy Antminer Z15 Pro in St Albans, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-stoke-on-trent",
        "keyword": "Buy Antminer Z15 Pro in Stoke-on-Trent, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sunderland",
        "keyword": "Buy Antminer Z15 Pro in Sunderland, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wakefield",
        "keyword": "Buy Antminer Z15 Pro in Wakefield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southend-on-sea",
        "keyword": "Buy ASIC Miner in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-southend-on-sea",
        "keyword": "Buy Bitmain Antminer S23 in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-newcastle-upon-tyne",
        "keyword": "Buy Bitmain Antminer S23 in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-norwich",
        "keyword": "Buy Bitmain Antminer S23 in Norwich, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nottingham",
        "keyword": "Buy Bitmain Antminer S23 in Nottingham, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-winchester",
      "place": "Winchester",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Winchester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-wakefield",
        "keyword": "Buy Antminer Z15 Pro in Wakefield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wells",
        "keyword": "Buy Antminer Z15 Pro in Wells, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-westminster",
        "keyword": "Buy Antminer Z15 Pro in Westminster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wolverhampton",
        "keyword": "Buy Antminer Z15 Pro in Wolverhampton, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-worcester",
        "keyword": "Buy Antminer Z15 Pro in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-york",
        "keyword": "Buy Antminer Z15 Pro in York, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-aberdeen",
        "keyword": "Buy Antminer Z15 Pro in Aberdeen, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-winchester",
        "keyword": "Buy ASIC Miner in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-winchester",
        "keyword": "Buy Bitmain Antminer S23 in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chester",
        "keyword": "Buy Bitmain Antminer S23 in Chester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chichester",
        "keyword": "Buy Bitmain Antminer S23 in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-colchester",
        "keyword": "Buy Bitmain Antminer S23 in Colchester, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-glasgow",
      "place": "Glasgow",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Glasgow, Scotland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-durham",
        "keyword": "Buy Antminer Z15 Pro in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ely",
        "keyword": "Buy Antminer Z15 Pro in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-exeter",
        "keyword": "Buy Antminer Z15 Pro in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gloucester",
        "keyword": "Buy Antminer Z15 Pro in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hereford",
        "keyword": "Buy Antminer Z15 Pro in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston-upon-hull",
        "keyword": "Buy Antminer Z15 Pro in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lancaster",
        "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-glasgow",
        "keyword": "Buy ASIC Miner in Glasgow, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-glasgow",
        "keyword": "Buy Bitmain Antminer S23 in Glasgow, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-armagh",
        "keyword": "Buy Antminer Z15 Pro in Armagh, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belfast",
        "keyword": "Buy Antminer Z15 Pro in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lisburn",
        "keyword": "Buy Antminer Z15 Pro in Lisburn, Northern Ireland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-idaho",
      "place": "Idaho",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Idaho"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-florida",
        "keyword": "Buy ASIC Miner in Florida"
      },
      {
        "slug": "buy-asic-miner-in-georgia",
        "keyword": "Buy ASIC Miner in Georgia"
      },
      {
        "slug": "buy-asic-miner-in-hawaii",
        "keyword": "Buy ASIC Miner in Hawaii"
      },
      {
        "slug": "buy-asic-miner-in-illinois",
        "keyword": "Buy ASIC Miner in Illinois"
      },
      {
        "slug": "buy-asic-miner-in-indiana",
        "keyword": "Buy ASIC Miner in Indiana"
      },
      {
        "slug": "buy-asic-miner-in-iowa",
        "keyword": "Buy ASIC Miner in Iowa"
      },
      {
        "slug": "buy-asic-miner-in-kansas",
        "keyword": "Buy ASIC Miner in Kansas"
      },
      {
        "slug": "buy-antminer-z15-pro-in-idaho",
        "keyword": "Buy Antminer Z15 Pro in Idaho"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-idaho",
        "keyword": "Buy Bitmain Antminer S23 in Idaho"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wisconsin",
        "keyword": "Buy Antminer Z15 Pro in Wisconsin"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wyoming",
        "keyword": "Buy Antminer Z15 Pro in Wyoming"
      },
      {
        "slug": "buy-asic-miner-in-alabama",
        "keyword": "Buy ASIC Miner in Alabama"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-kansas",
      "place": "Kansas",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Kansas"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-illinois",
        "keyword": "Buy ASIC Miner in Illinois"
      },
      {
        "slug": "buy-asic-miner-in-indiana",
        "keyword": "Buy ASIC Miner in Indiana"
      },
      {
        "slug": "buy-asic-miner-in-iowa",
        "keyword": "Buy ASIC Miner in Iowa"
      },
      {
        "slug": "buy-asic-miner-in-kentucky",
        "keyword": "Buy ASIC Miner in Kentucky"
      },
      {
        "slug": "buy-asic-miner-in-louisiana",
        "keyword": "Buy ASIC Miner in Louisiana"
      },
      {
        "slug": "buy-asic-miner-in-maine",
        "keyword": "Buy ASIC Miner in Maine"
      },
      {
        "slug": "buy-asic-miner-in-maryland",
        "keyword": "Buy ASIC Miner in Maryland"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kansas",
        "keyword": "Buy Antminer Z15 Pro in Kansas"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kansas",
        "keyword": "Buy Bitmain Antminer S23 in Kansas"
      },
      {
        "slug": "buy-asic-miner-in-west-virginia",
        "keyword": "Buy ASIC Miner in West Virginia"
      },
      {
        "slug": "buy-asic-miner-in-wisconsin",
        "keyword": "Buy ASIC Miner in Wisconsin"
      },
      {
        "slug": "buy-asic-miner-in-wyoming",
        "keyword": "Buy ASIC Miner in Wyoming"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-saguenay",
      "place": "Saguenay",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Saguenay, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-albert",
        "keyword": "Buy ASIC Miner in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-abbotsford",
        "keyword": "Buy ASIC Miner in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-burnaby",
        "keyword": "Buy ASIC Miner in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-coquitlam",
        "keyword": "Buy ASIC Miner in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-saguenay",
        "keyword": "Buy Antminer Z15 Pro in Saguenay, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-saguenay",
        "keyword": "Buy Bitmain Antminer S23 in Saguenay, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-prince-george",
        "keyword": "Buy ASIC Miner in Prince George, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-richmond",
        "keyword": "Buy ASIC Miner in Richmond, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-surrey",
        "keyword": "Buy ASIC Miner in Surrey, British Columbia, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-chelmsford",
      "place": "Chelmsford",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Chelmsford, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-bristol",
        "keyword": "Buy ASIC Miner in Bristol, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-canterbury",
        "keyword": "Buy ASIC Miner in Canterbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-carlisle",
        "keyword": "Buy ASIC Miner in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chester",
        "keyword": "Buy ASIC Miner in Chester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chichester",
        "keyword": "Buy ASIC Miner in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-colchester",
        "keyword": "Buy ASIC Miner in Colchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-coventry",
        "keyword": "Buy ASIC Miner in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chelmsford",
        "keyword": "Buy Antminer Z15 Pro in Chelmsford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chelmsford",
        "keyword": "Buy Bitmain Antminer S23 in Chelmsford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wolverhampton",
        "keyword": "Buy Antminer Z15 Pro in Wolverhampton, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-worcester",
        "keyword": "Buy Antminer Z15 Pro in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-york",
        "keyword": "Buy Antminer Z15 Pro in York, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-lancaster",
      "place": "Lancaster",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Lancaster, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-gloucester",
        "keyword": "Buy ASIC Miner in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-hereford",
        "keyword": "Buy ASIC Miner in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-kingston-upon-hull",
        "keyword": "Buy ASIC Miner in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leeds",
        "keyword": "Buy ASIC Miner in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leicester",
        "keyword": "Buy ASIC Miner in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lichfield",
        "keyword": "Buy ASIC Miner in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lincoln",
        "keyword": "Buy ASIC Miner in Lincoln, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lancaster",
        "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lancaster",
        "keyword": "Buy Bitmain Antminer S23 in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-coventry",
        "keyword": "Buy Bitmain Antminer S23 in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-derby",
        "keyword": "Buy Bitmain Antminer S23 in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-doncaster",
        "keyword": "Buy Bitmain Antminer S23 in Doncaster, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-portsmouth",
      "place": "Portsmouth",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Portsmouth, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-nottingham",
        "keyword": "Buy ASIC Miner in Nottingham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-oxford",
        "keyword": "Buy ASIC Miner in Oxford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-plymouth",
        "keyword": "Buy ASIC Miner in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-preston",
        "keyword": "Buy ASIC Miner in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-ripon",
        "keyword": "Buy ASIC Miner in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salford",
        "keyword": "Buy ASIC Miner in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salisbury",
        "keyword": "Buy ASIC Miner in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-portsmouth",
        "keyword": "Buy Antminer Z15 Pro in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-portsmouth",
        "keyword": "Buy Bitmain Antminer S23 in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-worcester",
        "keyword": "Buy Bitmain Antminer S23 in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-york",
        "keyword": "Buy Bitmain Antminer S23 in York, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-aberdeen",
        "keyword": "Buy Bitmain Antminer S23 in Aberdeen, Scotland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-inverness",
      "place": "Inverness",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Inverness, Scotland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-exeter",
        "keyword": "Buy ASIC Miner in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-gloucester",
        "keyword": "Buy ASIC Miner in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-hereford",
        "keyword": "Buy ASIC Miner in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-kingston-upon-hull",
        "keyword": "Buy ASIC Miner in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lancaster",
        "keyword": "Buy ASIC Miner in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leeds",
        "keyword": "Buy ASIC Miner in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-leicester",
        "keyword": "Buy ASIC Miner in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-inverness",
        "keyword": "Buy Antminer Z15 Pro in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-inverness",
        "keyword": "Buy Bitmain Antminer S23 in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-durham",
        "keyword": "Buy Bitmain Antminer S23 in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ely",
        "keyword": "Buy Bitmain Antminer S23 in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-exeter",
        "keyword": "Buy Bitmain Antminer S23 in Exeter, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-belfast",
      "place": "Belfast",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Belfast, Northern Ireland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-bath",
        "keyword": "Buy ASIC Miner in Bath, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-birmingham",
        "keyword": "Buy ASIC Miner in Birmingham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-bradford",
        "keyword": "Buy ASIC Miner in Bradford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-brighton-and-hove",
        "keyword": "Buy ASIC Miner in Brighton and Hove, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-bristol",
        "keyword": "Buy ASIC Miner in Bristol, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-canterbury",
        "keyword": "Buy ASIC Miner in Canterbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-carlisle",
        "keyword": "Buy ASIC Miner in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belfast",
        "keyword": "Buy Antminer Z15 Pro in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-belfast",
        "keyword": "Buy Bitmain Antminer S23 in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-salisbury",
        "keyword": "Buy ASIC Miner in Salisbury, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-sheffield",
        "keyword": "Buy ASIC Miner in Sheffield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southampton",
        "keyword": "Buy ASIC Miner in Southampton, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-idaho",
      "place": "Idaho",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Idaho"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-florida",
        "keyword": "Buy Bitmain Antminer S23 in Florida"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-georgia",
        "keyword": "Buy Bitmain Antminer S23 in Georgia"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-hawaii",
        "keyword": "Buy Bitmain Antminer S23 in Hawaii"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-illinois",
        "keyword": "Buy Bitmain Antminer S23 in Illinois"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-indiana",
        "keyword": "Buy Bitmain Antminer S23 in Indiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-iowa",
        "keyword": "Buy Bitmain Antminer S23 in Iowa"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kansas",
        "keyword": "Buy Bitmain Antminer S23 in Kansas"
      },
      {
        "slug": "buy-antminer-z15-pro-in-idaho",
        "keyword": "Buy Antminer Z15 Pro in Idaho"
      },
      {
        "slug": "buy-asic-miner-in-idaho",
        "keyword": "Buy ASIC Miner in Idaho"
      },
      {
        "slug": "buy-asic-miner-in-mississippi",
        "keyword": "Buy ASIC Miner in Mississippi"
      },
      {
        "slug": "buy-asic-miner-in-missouri",
        "keyword": "Buy ASIC Miner in Missouri"
      },
      {
        "slug": "buy-asic-miner-in-montana",
        "keyword": "Buy ASIC Miner in Montana"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-kansas",
      "place": "Kansas",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Kansas"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-illinois",
        "keyword": "Buy Bitmain Antminer S23 in Illinois"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-indiana",
        "keyword": "Buy Bitmain Antminer S23 in Indiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-iowa",
        "keyword": "Buy Bitmain Antminer S23 in Iowa"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kentucky",
        "keyword": "Buy Bitmain Antminer S23 in Kentucky"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-louisiana",
        "keyword": "Buy Bitmain Antminer S23 in Louisiana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-maine",
        "keyword": "Buy Bitmain Antminer S23 in Maine"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-maryland",
        "keyword": "Buy Bitmain Antminer S23 in Maryland"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kansas",
        "keyword": "Buy Antminer Z15 Pro in Kansas"
      },
      {
        "slug": "buy-asic-miner-in-kansas",
        "keyword": "Buy ASIC Miner in Kansas"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pennsylvania",
        "keyword": "Buy Antminer Z15 Pro in Pennsylvania"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rhode-island",
        "keyword": "Buy Antminer Z15 Pro in Rhode Island"
      },
      {
        "slug": "buy-antminer-z15-pro-in-south-carolina",
        "keyword": "Buy Antminer Z15 Pro in South Carolina"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-mississippi",
      "place": "Mississippi",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Mississippi"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-massachusetts",
        "keyword": "Buy Bitmain Antminer S23 in Massachusetts"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-michigan",
        "keyword": "Buy Bitmain Antminer S23 in Michigan"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-minnesota",
        "keyword": "Buy Bitmain Antminer S23 in Minnesota"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-missouri",
        "keyword": "Buy Bitmain Antminer S23 in Missouri"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-montana",
        "keyword": "Buy Bitmain Antminer S23 in Montana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nebraska",
        "keyword": "Buy Bitmain Antminer S23 in Nebraska"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nevada",
        "keyword": "Buy Bitmain Antminer S23 in Nevada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mississippi",
        "keyword": "Buy Antminer Z15 Pro in Mississippi"
      },
      {
        "slug": "buy-asic-miner-in-mississippi",
        "keyword": "Buy ASIC Miner in Mississippi"
      },
      {
        "slug": "buy-antminer-z15-pro-in-west-virginia",
        "keyword": "Buy Antminer Z15 Pro in West Virginia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wisconsin",
        "keyword": "Buy Antminer Z15 Pro in Wisconsin"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wyoming",
        "keyword": "Buy Antminer Z15 Pro in Wyoming"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-new-jersey",
      "place": "New Jersey",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in New Jersey"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-nebraska",
        "keyword": "Buy Bitmain Antminer S23 in Nebraska"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nevada",
        "keyword": "Buy Bitmain Antminer S23 in Nevada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-new-hampshire",
        "keyword": "Buy Bitmain Antminer S23 in New Hampshire"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-new-mexico",
        "keyword": "Buy Bitmain Antminer S23 in New Mexico"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-new-york",
        "keyword": "Buy Bitmain Antminer S23 in New York"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-north-carolina",
        "keyword": "Buy Bitmain Antminer S23 in North Carolina"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-north-dakota",
        "keyword": "Buy Bitmain Antminer S23 in North Dakota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-jersey",
        "keyword": "Buy Antminer Z15 Pro in New Jersey"
      },
      {
        "slug": "buy-asic-miner-in-new-jersey",
        "keyword": "Buy ASIC Miner in New Jersey"
      },
      {
        "slug": "buy-asic-miner-in-louisiana",
        "keyword": "Buy ASIC Miner in Louisiana"
      },
      {
        "slug": "buy-asic-miner-in-maine",
        "keyword": "Buy ASIC Miner in Maine"
      },
      {
        "slug": "buy-asic-miner-in-maryland",
        "keyword": "Buy ASIC Miner in Maryland"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-saguenay",
      "place": "Saguenay",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Saguenay, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-coquitlam",
        "keyword": "Buy Bitmain Antminer S23 in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-saguenay",
        "keyword": "Buy Antminer Z15 Pro in Saguenay, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-saguenay",
        "keyword": "Buy ASIC Miner in Saguenay, Quebec, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dartmouth",
        "keyword": "Buy Antminer Z15 Pro in Dartmouth, Nova Scotia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-halifax",
        "keyword": "Buy Antminer Z15 Pro in Halifax, Nova Scotia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-truro",
        "keyword": "Buy Antminer Z15 Pro in Truro, Nova Scotia, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-lancaster",
      "place": "Lancaster",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Lancaster, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-gloucester",
        "keyword": "Buy Bitmain Antminer S23 in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-hereford",
        "keyword": "Buy Bitmain Antminer S23 in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kingston-upon-hull",
        "keyword": "Buy Bitmain Antminer S23 in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-leeds",
        "keyword": "Buy Bitmain Antminer S23 in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-leicester",
        "keyword": "Buy Bitmain Antminer S23 in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lichfield",
        "keyword": "Buy Bitmain Antminer S23 in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lincoln",
        "keyword": "Buy Bitmain Antminer S23 in Lincoln, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lancaster",
        "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lancaster",
        "keyword": "Buy ASIC Miner in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-stoke-on-trent",
        "keyword": "Buy Bitmain Antminer S23 in Stoke-on-Trent, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-sunderland",
        "keyword": "Buy Bitmain Antminer S23 in Sunderland, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-wakefield",
        "keyword": "Buy Bitmain Antminer S23 in Wakefield, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-inverness",
      "place": "Inverness",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Inverness, Scotland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-exeter",
        "keyword": "Buy Bitmain Antminer S23 in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-gloucester",
        "keyword": "Buy Bitmain Antminer S23 in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-hereford",
        "keyword": "Buy Bitmain Antminer S23 in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kingston-upon-hull",
        "keyword": "Buy Bitmain Antminer S23 in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lancaster",
        "keyword": "Buy Bitmain Antminer S23 in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-leeds",
        "keyword": "Buy Bitmain Antminer S23 in Leeds, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-leicester",
        "keyword": "Buy Bitmain Antminer S23 in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-inverness",
        "keyword": "Buy Antminer Z15 Pro in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-inverness",
        "keyword": "Buy ASIC Miner in Inverness, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ripon",
        "keyword": "Buy Antminer Z15 Pro in Ripon, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salford",
        "keyword": "Buy Antminer Z15 Pro in Salford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salisbury",
        "keyword": "Buy Antminer Z15 Pro in Salisbury, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-belfast",
      "place": "Belfast",
      "country": "United Kingdom",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Belfast, Northern Ireland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-bath",
        "keyword": "Buy Bitmain Antminer S23 in Bath, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-birmingham",
        "keyword": "Buy Bitmain Antminer S23 in Birmingham, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-bradford",
        "keyword": "Buy Bitmain Antminer S23 in Bradford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-brighton-and-hove",
        "keyword": "Buy Bitmain Antminer S23 in Brighton and Hove, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-bristol",
        "keyword": "Buy Bitmain Antminer S23 in Bristol, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-canterbury",
        "keyword": "Buy Bitmain Antminer S23 in Canterbury, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-carlisle",
        "keyword": "Buy Bitmain Antminer S23 in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belfast",
        "keyword": "Buy Antminer Z15 Pro in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-belfast",
        "keyword": "Buy ASIC Miner in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-exeter",
        "keyword": "Buy ASIC Miner in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-gloucester",
        "keyword": "Buy ASIC Miner in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-hereford",
        "keyword": "Buy ASIC Miner in Hereford, England, United Kingdom"
      }
    ]
  }
];
