// AUTO-GENERATED by scripts/build-marketplace-shards.ts — do not edit.
import type { LocationEntry } from "./types";

export const ENTRIES: LocationEntry[] = [
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-alkmaar",
      "place": "Alkmaar",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Alkmaar, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-almelo",
        "keyword": "Buy Antminer Z15 Pro in Almelo, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-almere",
        "keyword": "Buy Antminer Z15 Pro in Almere, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-amersfoort",
        "keyword": "Buy Antminer Z15 Pro in Amersfoort, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-amstelveen",
        "keyword": "Buy Antminer Z15 Pro in Amstelveen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-amsterdam",
        "keyword": "Buy Antminer Z15 Pro in Amsterdam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-apeldoorn",
        "keyword": "Buy Antminer Z15 Pro in Apeldoorn, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arnhem",
        "keyword": "Buy Antminer Z15 Pro in Arnhem, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schiedam",
        "keyword": "Buy Antminer Z15 Pro in Schiedam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sittard",
        "keyword": "Buy Antminer Z15 Pro in Sittard, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-spijkenisse",
        "keyword": "Buy Antminer Z15 Pro in Spijkenisse, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tilburg",
        "keyword": "Buy Antminer Z15 Pro in Tilburg, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-utrecht",
        "keyword": "Buy Antminer Z15 Pro in Utrecht, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-sittard",
      "place": "Sittard",
      "country": "Netherlands",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Sittard, Netherlands"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-roosendaal",
        "keyword": "Buy Antminer Z15 Pro in Roosendaal, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rotterdam",
        "keyword": "Buy Antminer Z15 Pro in Rotterdam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-schiedam",
        "keyword": "Buy Antminer Z15 Pro in Schiedam, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-spijkenisse",
        "keyword": "Buy Antminer Z15 Pro in Spijkenisse, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tilburg",
        "keyword": "Buy Antminer Z15 Pro in Tilburg, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-utrecht",
        "keyword": "Buy Antminer Z15 Pro in Utrecht, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-veenendaal",
        "keyword": "Buy Antminer Z15 Pro in Veenendaal, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-assen",
        "keyword": "Buy Antminer Z15 Pro in Assen, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bergen-op-zoom",
        "keyword": "Buy Antminer Z15 Pro in Bergen op Zoom, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-beverwijk",
        "keyword": "Buy Antminer Z15 Pro in Beverwijk, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-breda",
        "keyword": "Buy Antminer Z15 Pro in Breda, Netherlands"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delft",
        "keyword": "Buy Antminer Z15 Pro in Delft, Netherlands"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-kaiserslautern",
      "place": "Kaiserslautern",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Kaiserslautern, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-hildesheim",
        "keyword": "Buy Antminer Z15 Pro in Hildesheim, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ingolstadt",
        "keyword": "Buy Antminer Z15 Pro in Ingolstadt, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-jena",
        "keyword": "Buy Antminer Z15 Pro in Jena, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-karlsruhe",
        "keyword": "Buy Antminer Z15 Pro in Karlsruhe, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kassel",
        "keyword": "Buy Antminer Z15 Pro in Kassel, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kaufbeuren",
        "keyword": "Buy Antminer Z15 Pro in Kaufbeuren, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kempten",
        "keyword": "Buy Antminer Z15 Pro in Kempten, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-speyer",
        "keyword": "Buy Antminer Z15 Pro in Speyer, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-stuttgart",
        "keyword": "Buy Antminer Z15 Pro in Stuttgart, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-trier",
        "keyword": "Buy Antminer Z15 Pro in Trier, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ulm",
        "keyword": "Buy Antminer Z15 Pro in Ulm, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-villingen-schwenningen",
        "keyword": "Buy Antminer Z15 Pro in Villingen-Schwenningen, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lüneburg",
      "place": "Lüneburg",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lüneburg, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-ludwigsburg",
        "keyword": "Buy Antminer Z15 Pro in Ludwigsburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ludwigshafen",
        "keyword": "Buy Antminer Z15 Pro in Ludwigshafen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lübeck",
        "keyword": "Buy Antminer Z15 Pro in Lübeck, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-magdeburg",
        "keyword": "Buy Antminer Z15 Pro in Magdeburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mainz",
        "keyword": "Buy Antminer Z15 Pro in Mainz, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mannheim",
        "keyword": "Buy Antminer Z15 Pro in Mannheim, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-marburg",
        "keyword": "Buy Antminer Z15 Pro in Marburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hamm",
        "keyword": "Buy Antminer Z15 Pro in Hamm, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hanau",
        "keyword": "Buy Antminer Z15 Pro in Hanau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hannover",
        "keyword": "Buy Antminer Z15 Pro in Hannover, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-heidelberg",
        "keyword": "Buy Antminer Z15 Pro in Heidelberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-heilbronn",
        "keyword": "Buy Antminer Z15 Pro in Heilbronn, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-münchen",
      "place": "München",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in München, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-marburg",
        "keyword": "Buy Antminer Z15 Pro in Marburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mönchengladbach",
        "keyword": "Buy Antminer Z15 Pro in Mönchengladbach, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mülheim-an-der-ruhr",
        "keyword": "Buy Antminer Z15 Pro in Mülheim an der Ruhr, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-münster",
        "keyword": "Buy Antminer Z15 Pro in Münster, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neubrandenburg",
        "keyword": "Buy Antminer Z15 Pro in Neubrandenburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neumünster",
        "keyword": "Buy Antminer Z15 Pro in Neumünster, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neuss",
        "keyword": "Buy Antminer Z15 Pro in Neuss, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mannheim",
        "keyword": "Buy Antminer Z15 Pro in Mannheim, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nürnberg",
        "keyword": "Buy Antminer Z15 Pro in Nürnberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oberhausen",
        "keyword": "Buy Antminer Z15 Pro in Oberhausen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-offenbach-am-main",
        "keyword": "Buy Antminer Z15 Pro in Offenbach am Main, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oldenburg",
        "keyword": "Buy Antminer Z15 Pro in Oldenburg, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-neumünster",
      "place": "Neumünster",
      "country": "Germany",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Neumünster, Germany"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-münchen",
        "keyword": "Buy Antminer Z15 Pro in München, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-münster",
        "keyword": "Buy Antminer Z15 Pro in Münster, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neubrandenburg",
        "keyword": "Buy Antminer Z15 Pro in Neubrandenburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-neuss",
        "keyword": "Buy Antminer Z15 Pro in Neuss, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nürnberg",
        "keyword": "Buy Antminer Z15 Pro in Nürnberg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oberhausen",
        "keyword": "Buy Antminer Z15 Pro in Oberhausen, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-offenbach-am-main",
        "keyword": "Buy Antminer Z15 Pro in Offenbach am Main, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oldenburg",
        "keyword": "Buy Antminer Z15 Pro in Oldenburg, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-osnabrück",
        "keyword": "Buy Antminer Z15 Pro in Osnabrück, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-paderborn",
        "keyword": "Buy Antminer Z15 Pro in Paderborn, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-passau",
        "keyword": "Buy Antminer Z15 Pro in Passau, Germany"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pforzheim",
        "keyword": "Buy Antminer Z15 Pro in Pforzheim, Germany"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-vienna",
      "place": "Vienna",
      "country": "Austria",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Vienna, Austria"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-ternitz",
        "keyword": "Buy Antminer Z15 Pro in Ternitz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traiskirchen",
        "keyword": "Buy Antminer Z15 Pro in Traiskirchen, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-traun",
        "keyword": "Buy Antminer Z15 Pro in Traun, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-villach",
        "keyword": "Buy Antminer Z15 Pro in Villach, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vöcklabruck",
        "keyword": "Buy Antminer Z15 Pro in Vöcklabruck, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wels",
        "keyword": "Buy Antminer Z15 Pro in Wels, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wien",
        "keyword": "Buy Antminer Z15 Pro in Wien, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gmunden",
        "keyword": "Buy Antminer Z15 Pro in Gmunden, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-graz",
        "keyword": "Buy Antminer Z15 Pro in Graz, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gänserndorf",
        "keyword": "Buy Antminer Z15 Pro in Gänserndorf, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hallein",
        "keyword": "Buy Antminer Z15 Pro in Hallein, Austria"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hollabrunn",
        "keyword": "Buy Antminer Z15 Pro in Hollabrunn, Austria"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-melbourne",
      "place": "Melbourne",
      "country": "Australia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Melbourne, Australia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-launceston",
        "keyword": "Buy Antminer Z15 Pro in Launceston, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mackay",
        "keyword": "Buy Antminer Z15 Pro in Mackay, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mandurah",
        "keyword": "Buy Antminer Z15 Pro in Mandurah, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mildura",
        "keyword": "Buy Antminer Z15 Pro in Mildura, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mount-gambier",
        "keyword": "Buy Antminer Z15 Pro in Mount Gambier, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newcastle",
        "keyword": "Buy Antminer Z15 Pro in Newcastle, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nowra",
        "keyword": "Buy Antminer Z15 Pro in Nowra, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-augusta",
        "keyword": "Buy Antminer Z15 Pro in Port Augusta, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-hedland",
        "keyword": "Buy Antminer Z15 Pro in Port Hedland, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-port-macquarie",
        "keyword": "Buy Antminer Z15 Pro in Port Macquarie, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rockhampton",
        "keyword": "Buy Antminer Z15 Pro in Rockhampton, Australia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shepparton",
        "keyword": "Buy Antminer Z15 Pro in Shepparton, Australia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-kiev",
      "place": "Kiev",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Kiev, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-khmelnytskyi",
        "keyword": "Buy Antminer Z15 Pro in Khmelnytskyi, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khmilnyk",
        "keyword": "Buy Antminer Z15 Pro in Khmilnyk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-khorol",
        "keyword": "Buy Antminer Z15 Pro in Khorol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kirovohrad",
        "keyword": "Buy Antminer Z15 Pro in Kirovohrad, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kovel",
        "keyword": "Buy Antminer Z15 Pro in Kovel, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kremenchuk",
        "keyword": "Buy Antminer Z15 Pro in Kremenchuk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kryvyi-rih",
        "keyword": "Buy Antminer Z15 Pro in Kryvyi Rih, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyiv",
        "keyword": "Buy Antminer Z15 Pro in Kyiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lviv",
        "keyword": "Buy Antminer Z15 Pro in Lviv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mariupol",
        "keyword": "Buy Antminer Z15 Pro in Mariupol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-melitopol",
        "keyword": "Buy Antminer Z15 Pro in Melitopol, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lviv",
      "place": "Lviv",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lviv, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-kryvyi-rih",
        "keyword": "Buy Antminer Z15 Pro in Kryvyi Rih, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyiv",
        "keyword": "Buy Antminer Z15 Pro in Kyiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mariupol",
        "keyword": "Buy Antminer Z15 Pro in Mariupol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-melitopol",
        "keyword": "Buy Antminer Z15 Pro in Melitopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mukachevo",
        "keyword": "Buy Antminer Z15 Pro in Mukachevo, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mykolaiv",
        "keyword": "Buy Antminer Z15 Pro in Mykolaiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-yalta",
        "keyword": "Buy Antminer Z15 Pro in Yalta, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zaporizhzhia",
        "keyword": "Buy Antminer Z15 Pro in Zaporizhzhia, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zhytomyr",
        "keyword": "Buy Antminer Z15 Pro in Zhytomyr, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-alchevsk",
        "keyword": "Buy Antminer Z15 Pro in Alchevsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bakhmut",
        "keyword": "Buy Antminer Z15 Pro in Bakhmut, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-melitopol",
      "place": "Melitopol",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Melitopol, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lviv",
        "keyword": "Buy Antminer Z15 Pro in Lviv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mariupol",
        "keyword": "Buy Antminer Z15 Pro in Mariupol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mukachevo",
        "keyword": "Buy Antminer Z15 Pro in Mukachevo, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mykolaiv",
        "keyword": "Buy Antminer Z15 Pro in Mykolaiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nizhyn",
        "keyword": "Buy Antminer Z15 Pro in Nizhyn, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-odesa",
        "keyword": "Buy Antminer Z15 Pro in Odesa, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sevastopol",
        "keyword": "Buy Antminer Z15 Pro in Sevastopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shostka",
        "keyword": "Buy Antminer Z15 Pro in Shostka, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-simferopol",
        "keyword": "Buy Antminer Z15 Pro in Simferopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sloviansk",
        "keyword": "Buy Antminer Z15 Pro in Sloviansk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sumy",
        "keyword": "Buy Antminer Z15 Pro in Sumy, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-poltava",
      "place": "Poltava",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Poltava, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-nizhyn",
        "keyword": "Buy Antminer Z15 Pro in Nizhyn, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-odesa",
        "keyword": "Buy Antminer Z15 Pro in Odesa, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pavlohrad",
        "keyword": "Buy Antminer Z15 Pro in Pavlohrad, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rivne",
        "keyword": "Buy Antminer Z15 Pro in Rivne, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sevastopol",
        "keyword": "Buy Antminer Z15 Pro in Sevastopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-shostka",
        "keyword": "Buy Antminer Z15 Pro in Shostka, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-simferopol",
        "keyword": "Buy Antminer Z15 Pro in Simferopol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyiv",
        "keyword": "Buy Antminer Z15 Pro in Kyiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lviv",
        "keyword": "Buy Antminer Z15 Pro in Lviv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mariupol",
        "keyword": "Buy Antminer Z15 Pro in Mariupol, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-melitopol",
        "keyword": "Buy Antminer Z15 Pro in Melitopol, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-vinnytsia",
      "place": "Vinnytsia",
      "country": "Ukraine",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Vinnytsia, Ukraine"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-sumy",
        "keyword": "Buy Antminer Z15 Pro in Sumy, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ternopil",
        "keyword": "Buy Antminer Z15 Pro in Ternopil, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-uzhhorod",
        "keyword": "Buy Antminer Z15 Pro in Uzhhorod, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-volodymyr",
        "keyword": "Buy Antminer Z15 Pro in Volodymyr, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-yalta",
        "keyword": "Buy Antminer Z15 Pro in Yalta, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zaporizhzhia",
        "keyword": "Buy Antminer Z15 Pro in Zaporizhzhia, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-zhytomyr",
        "keyword": "Buy Antminer Z15 Pro in Zhytomyr, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kremenchuk",
        "keyword": "Buy Antminer Z15 Pro in Kremenchuk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kryvyi-rih",
        "keyword": "Buy Antminer Z15 Pro in Kryvyi Rih, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kyiv",
        "keyword": "Buy Antminer Z15 Pro in Kyiv, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lutsk",
        "keyword": "Buy Antminer Z15 Pro in Lutsk, Ukraine"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lviv",
        "keyword": "Buy Antminer Z15 Pro in Lviv, Ukraine"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-barnaul",
      "place": "Barnaul",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Barnaul, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-armavir",
        "keyword": "Buy Antminer Z15 Pro in Armavir, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-astrakhan",
        "keyword": "Buy Antminer Z15 Pro in Astrakhan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-balakovo",
        "keyword": "Buy Antminer Z15 Pro in Balakovo, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belgorod",
        "keyword": "Buy Antminer Z15 Pro in Belgorod, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-biysk",
        "keyword": "Buy Antminer Z15 Pro in Biysk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-blagoveshchensk",
        "keyword": "Buy Antminer Z15 Pro in Blagoveshchensk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bratsk",
        "keyword": "Buy Antminer Z15 Pro in Bratsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-stavropol",
        "keyword": "Buy Antminer Z15 Pro in Stavropol, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sterlitamak",
        "keyword": "Buy Antminer Z15 Pro in Sterlitamak, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-surgut",
        "keyword": "Buy Antminer Z15 Pro in Surgut, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-syktyvkar",
        "keyword": "Buy Antminer Z15 Pro in Syktyvkar, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tambov",
        "keyword": "Buy Antminer Z15 Pro in Tambov, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-rostov-on-don",
      "place": "Rostov-on-Don",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Rostov-on-Don, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-petropavlovsk-kamchatsky",
        "keyword": "Buy Antminer Z15 Pro in Petropavlovsk-Kamchatsky, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-petrozavodsk",
        "keyword": "Buy Antminer Z15 Pro in Petrozavodsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pskov",
        "keyword": "Buy Antminer Z15 Pro in Pskov, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ryazan",
        "keyword": "Buy Antminer Z15 Pro in Ryazan, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-salekhard",
        "keyword": "Buy Antminer Z15 Pro in Salekhard, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-samara",
        "keyword": "Buy Antminer Z15 Pro in Samara, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-saransk",
        "keyword": "Buy Antminer Z15 Pro in Saransk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-barnaul",
        "keyword": "Buy Antminer Z15 Pro in Barnaul, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belgorod",
        "keyword": "Buy Antminer Z15 Pro in Belgorod, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-biysk",
        "keyword": "Buy Antminer Z15 Pro in Biysk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-blagoveshchensk",
        "keyword": "Buy Antminer Z15 Pro in Blagoveshchensk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bratsk",
        "keyword": "Buy Antminer Z15 Pro in Bratsk, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-tver",
      "place": "Tver",
      "country": "Russia",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Tver, Russia"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-tolyatti",
        "keyword": "Buy Antminer Z15 Pro in Tolyatti, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tomsk",
        "keyword": "Buy Antminer Z15 Pro in Tomsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tula",
        "keyword": "Buy Antminer Z15 Pro in Tula, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tyumen",
        "keyword": "Buy Antminer Z15 Pro in Tyumen, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ufa",
        "keyword": "Buy Antminer Z15 Pro in Ufa, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ulan-ude",
        "keyword": "Buy Antminer Z15 Pro in Ulan-Ude, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ulyanovsk",
        "keyword": "Buy Antminer Z15 Pro in Ulyanovsk, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vladikavkaz",
        "keyword": "Buy Antminer Z15 Pro in Vladikavkaz, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vladimir",
        "keyword": "Buy Antminer Z15 Pro in Vladimir, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vladivostok",
        "keyword": "Buy Antminer Z15 Pro in Vladivostok, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-volgograd",
        "keyword": "Buy Antminer Z15 Pro in Volgograd, Russia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vologda",
        "keyword": "Buy Antminer Z15 Pro in Vologda, Russia"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-alost",
      "place": "Alost",
      "country": "Belgium",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Alost, Belgium"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-antwerp",
        "keyword": "Buy Antminer Z15 Pro in Antwerp, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arlon",
        "keyword": "Buy Antminer Z15 Pro in Arlon, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bruges",
        "keyword": "Buy Antminer Z15 Pro in Bruges, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brussels",
        "keyword": "Buy Antminer Z15 Pro in Brussels, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-charleroi",
        "keyword": "Buy Antminer Z15 Pro in Charleroi, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dendermonde",
        "keyword": "Buy Antminer Z15 Pro in Dendermonde, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-genk",
        "keyword": "Buy Antminer Z15 Pro in Genk, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ypres",
        "keyword": "Buy Antminer Z15 Pro in Ypres, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ghent",
        "keyword": "Buy Antminer Z15 Pro in Ghent, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hasselt",
        "keyword": "Buy Antminer Z15 Pro in Hasselt, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-herentals",
        "keyword": "Buy Antminer Z15 Pro in Herentals, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-huy",
        "keyword": "Buy Antminer Z15 Pro in Huy, Belgium"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-brussels",
      "place": "Brussels",
      "country": "Belgium",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Brussels, Belgium"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-antwerp",
        "keyword": "Buy Antminer Z15 Pro in Antwerp, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-arlon",
        "keyword": "Buy Antminer Z15 Pro in Arlon, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bruges",
        "keyword": "Buy Antminer Z15 Pro in Bruges, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-charleroi",
        "keyword": "Buy Antminer Z15 Pro in Charleroi, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dendermonde",
        "keyword": "Buy Antminer Z15 Pro in Dendermonde, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-genk",
        "keyword": "Buy Antminer Z15 Pro in Genk, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ghent",
        "keyword": "Buy Antminer Z15 Pro in Ghent, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ninove",
        "keyword": "Buy Antminer Z15 Pro in Ninove, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ostend",
        "keyword": "Buy Antminer Z15 Pro in Ostend, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-roeselare",
        "keyword": "Buy Antminer Z15 Pro in Roeselare, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-sint-niklaas",
        "keyword": "Buy Antminer Z15 Pro in Sint-Niklaas, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-soignies",
        "keyword": "Buy Antminer Z15 Pro in Soignies, Belgium"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-charleroi",
      "place": "Charleroi",
      "country": "Belgium",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Charleroi, Belgium"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-arlon",
        "keyword": "Buy Antminer Z15 Pro in Arlon, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bruges",
        "keyword": "Buy Antminer Z15 Pro in Bruges, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brussels",
        "keyword": "Buy Antminer Z15 Pro in Brussels, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dendermonde",
        "keyword": "Buy Antminer Z15 Pro in Dendermonde, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-genk",
        "keyword": "Buy Antminer Z15 Pro in Genk, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ghent",
        "keyword": "Buy Antminer Z15 Pro in Ghent, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hasselt",
        "keyword": "Buy Antminer Z15 Pro in Hasselt, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-waterloo",
        "keyword": "Buy Antminer Z15 Pro in Waterloo, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-wavre",
        "keyword": "Buy Antminer Z15 Pro in Wavre, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ypres",
        "keyword": "Buy Antminer Z15 Pro in Ypres, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-alost",
        "keyword": "Buy Antminer Z15 Pro in Alost, Belgium"
      },
      {
        "slug": "buy-antminer-z15-pro-in-antwerp",
        "keyword": "Buy Antminer Z15 Pro in Antwerp, Belgium"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-idaho",
      "place": "Idaho",
      "country": "United States",
      "type": "state",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Idaho"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-florida",
        "keyword": "Buy Antminer Z15 Pro in Florida"
      },
      {
        "slug": "buy-antminer-z15-pro-in-georgia",
        "keyword": "Buy Antminer Z15 Pro in Georgia"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hawaii",
        "keyword": "Buy Antminer Z15 Pro in Hawaii"
      },
      {
        "slug": "buy-antminer-z15-pro-in-illinois",
        "keyword": "Buy Antminer Z15 Pro in Illinois"
      },
      {
        "slug": "buy-antminer-z15-pro-in-indiana",
        "keyword": "Buy Antminer Z15 Pro in Indiana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-iowa",
        "keyword": "Buy Antminer Z15 Pro in Iowa"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kansas",
        "keyword": "Buy Antminer Z15 Pro in Kansas"
      },
      {
        "slug": "buy-asic-miner-in-idaho",
        "keyword": "Buy ASIC Miner in Idaho"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-idaho",
        "keyword": "Buy Bitmain Antminer S23 in Idaho"
      },
      {
        "slug": "buy-antminer-z15-pro-in-north-dakota",
        "keyword": "Buy Antminer Z15 Pro in North Dakota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ohio",
        "keyword": "Buy Antminer Z15 Pro in Ohio"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oklahoma",
        "keyword": "Buy Antminer Z15 Pro in Oklahoma"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-nevada",
      "place": "Nevada",
      "country": "United States",
      "type": "state",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Nevada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-missouri",
        "keyword": "Buy Antminer Z15 Pro in Missouri"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montana",
        "keyword": "Buy Antminer Z15 Pro in Montana"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nebraska",
        "keyword": "Buy Antminer Z15 Pro in Nebraska"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-hampshire",
        "keyword": "Buy Antminer Z15 Pro in New Hampshire"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-jersey",
        "keyword": "Buy Antminer Z15 Pro in New Jersey"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-mexico",
        "keyword": "Buy Antminer Z15 Pro in New Mexico"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-york",
        "keyword": "Buy Antminer Z15 Pro in New York"
      },
      {
        "slug": "buy-asic-miner-in-nevada",
        "keyword": "Buy ASIC Miner in Nevada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nevada",
        "keyword": "Buy Bitmain Antminer S23 in Nevada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-texas",
        "keyword": "Buy Bitmain Antminer S23 in Texas"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-utah",
        "keyword": "Buy Bitmain Antminer S23 in Utah"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-vermont",
        "keyword": "Buy Bitmain Antminer S23 in Vermont"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-ohio",
      "place": "Ohio",
      "country": "United States",
      "type": "state",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Ohio"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-new-york",
        "keyword": "Buy Antminer Z15 Pro in New York"
      },
      {
        "slug": "buy-antminer-z15-pro-in-north-carolina",
        "keyword": "Buy Antminer Z15 Pro in North Carolina"
      },
      {
        "slug": "buy-antminer-z15-pro-in-north-dakota",
        "keyword": "Buy Antminer Z15 Pro in North Dakota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oklahoma",
        "keyword": "Buy Antminer Z15 Pro in Oklahoma"
      },
      {
        "slug": "buy-antminer-z15-pro-in-oregon",
        "keyword": "Buy Antminer Z15 Pro in Oregon"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pennsylvania",
        "keyword": "Buy Antminer Z15 Pro in Pennsylvania"
      },
      {
        "slug": "buy-antminer-z15-pro-in-rhode-island",
        "keyword": "Buy Antminer Z15 Pro in Rhode Island"
      },
      {
        "slug": "buy-asic-miner-in-ohio",
        "keyword": "Buy ASIC Miner in Ohio"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ohio",
        "keyword": "Buy Bitmain Antminer S23 in Ohio"
      },
      {
        "slug": "buy-antminer-z15-pro-in-south-carolina",
        "keyword": "Buy Antminer Z15 Pro in South Carolina"
      },
      {
        "slug": "buy-antminer-z15-pro-in-south-dakota",
        "keyword": "Buy Antminer Z15 Pro in South Dakota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tennessee",
        "keyword": "Buy Antminer Z15 Pro in Tennessee"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-vancouver",
      "place": "Vancouver",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Vancouver, British Columbia, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-prince-george",
        "keyword": "Buy Antminer Z15 Pro in Prince George, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-richmond",
        "keyword": "Buy Antminer Z15 Pro in Richmond, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-surrey",
        "keyword": "Buy Antminer Z15 Pro in Surrey, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-victoria",
        "keyword": "Buy Antminer Z15 Pro in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brandon",
        "keyword": "Buy Antminer Z15 Pro in Brandon, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-winnipeg",
        "keyword": "Buy Antminer Z15 Pro in Winnipeg, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dieppe",
        "keyword": "Buy Antminer Z15 Pro in Dieppe, New Brunswick, Canada"
      },
      {
        "slug": "buy-asic-miner-in-vancouver",
        "keyword": "Buy ASIC Miner in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-vancouver",
        "keyword": "Buy Bitmain Antminer S23 in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-yellowknife",
        "keyword": "Buy Bitmain Antminer S23 in Yellowknife, Northwest Territories, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-iqaluit",
        "keyword": "Buy Bitmain Antminer S23 in Iqaluit, Nunavut, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-whitehorse",
        "keyword": "Buy Bitmain Antminer S23 in Whitehorse, Yukon, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-victoria",
      "place": "Victoria",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Victoria, British Columbia, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-surrey",
        "keyword": "Buy Antminer Z15 Pro in Surrey, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-vancouver",
        "keyword": "Buy Antminer Z15 Pro in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brandon",
        "keyword": "Buy Antminer Z15 Pro in Brandon, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-winnipeg",
        "keyword": "Buy Antminer Z15 Pro in Winnipeg, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dieppe",
        "keyword": "Buy Antminer Z15 Pro in Dieppe, New Brunswick, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-fredericton",
        "keyword": "Buy Antminer Z15 Pro in Fredericton, New Brunswick, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-moncton",
        "keyword": "Buy Antminer Z15 Pro in Moncton, New Brunswick, Canada"
      },
      {
        "slug": "buy-asic-miner-in-victoria",
        "keyword": "Buy ASIC Miner in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-victoria",
        "keyword": "Buy Bitmain Antminer S23 in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-guelph",
        "keyword": "Buy Bitmain Antminer S23 in Guelph, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-hamilton",
        "keyword": "Buy Bitmain Antminer S23 in Hamilton, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-kingston",
        "keyword": "Buy Bitmain Antminer S23 in Kingston, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-iqaluit",
      "place": "Iqaluit",
      "country": "Canada",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Iqaluit, Nunavut, Canada"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-calgary",
        "keyword": "Buy Antminer Z15 Pro in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-edmonton",
        "keyword": "Buy Antminer Z15 Pro in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-grande-prairie",
        "keyword": "Buy Antminer Z15 Pro in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lethbridge",
        "keyword": "Buy Antminer Z15 Pro in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-medicine-hat",
        "keyword": "Buy Antminer Z15 Pro in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-albert",
        "keyword": "Buy Antminer Z15 Pro in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-iqaluit",
        "keyword": "Buy ASIC Miner in Iqaluit, Nunavut, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-iqaluit",
        "keyword": "Buy Bitmain Antminer S23 in Iqaluit, Nunavut, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ottawa",
        "keyword": "Buy Antminer Z15 Pro in Ottawa, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-peterborough",
        "keyword": "Buy Antminer Z15 Pro in Peterborough, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pickering",
        "keyword": "Buy Antminer Z15 Pro in Pickering, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-exeter",
      "place": "Exeter",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Exeter, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-doncaster",
        "keyword": "Buy Antminer Z15 Pro in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-durham",
        "keyword": "Buy Antminer Z15 Pro in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ely",
        "keyword": "Buy Antminer Z15 Pro in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gloucester",
        "keyword": "Buy Antminer Z15 Pro in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-hereford",
        "keyword": "Buy Antminer Z15 Pro in Hereford, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston-upon-hull",
        "keyword": "Buy Antminer Z15 Pro in Kingston upon Hull, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lancaster",
        "keyword": "Buy Antminer Z15 Pro in Lancaster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-exeter",
        "keyword": "Buy ASIC Miner in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-exeter",
        "keyword": "Buy Bitmain Antminer S23 in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-portsmouth",
        "keyword": "Buy Bitmain Antminer S23 in Portsmouth, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-preston",
        "keyword": "Buy Bitmain Antminer S23 in Preston, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-ripon",
        "keyword": "Buy Bitmain Antminer S23 in Ripon, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-dundee",
      "place": "Dundee",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Dundee, Scotland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-coventry",
        "keyword": "Buy Antminer Z15 Pro in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-derby",
        "keyword": "Buy Antminer Z15 Pro in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-doncaster",
        "keyword": "Buy Antminer Z15 Pro in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-durham",
        "keyword": "Buy Antminer Z15 Pro in Durham, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-ely",
        "keyword": "Buy Antminer Z15 Pro in Ely, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-exeter",
        "keyword": "Buy Antminer Z15 Pro in Exeter, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gloucester",
        "keyword": "Buy Antminer Z15 Pro in Gloucester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-dundee",
        "keyword": "Buy ASIC Miner in Dundee, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-dundee",
        "keyword": "Buy Bitmain Antminer S23 in Dundee, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-belfast",
        "keyword": "Buy Antminer Z15 Pro in Belfast, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lisburn",
        "keyword": "Buy Antminer Z15 Pro in Lisburn, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-londonderry",
        "keyword": "Buy Antminer Z15 Pro in Londonderry, Northern Ireland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-antminer-z15-pro-in-lisburn",
      "place": "Lisburn",
      "country": "United Kingdom",
      "type": "city",
      "family": "z15",
      "keyword": "Buy Antminer Z15 Pro in Lisburn, Northern Ireland, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-antminer-z15-pro-in-leicester",
        "keyword": "Buy Antminer Z15 Pro in Leicester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lichfield",
        "keyword": "Buy Antminer Z15 Pro in Lichfield, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-lincoln",
        "keyword": "Buy Antminer Z15 Pro in Lincoln, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-liverpool",
        "keyword": "Buy Antminer Z15 Pro in Liverpool, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-manchester",
        "keyword": "Buy Antminer Z15 Pro in Manchester, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-milton-keynes",
        "keyword": "Buy Antminer Z15 Pro in Milton Keynes, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newcastle-upon-tyne",
        "keyword": "Buy Antminer Z15 Pro in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-lisburn",
        "keyword": "Buy ASIC Miner in Lisburn, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lisburn",
        "keyword": "Buy Bitmain Antminer S23 in Lisburn, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-birmingham",
        "keyword": "Buy Bitmain Antminer S23 in Birmingham, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-bradford",
        "keyword": "Buy Bitmain Antminer S23 in Bradford, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-brighton-and-hove",
        "keyword": "Buy Bitmain Antminer S23 in Brighton and Hove, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-new-mexico",
      "place": "New Mexico",
      "country": "United States",
      "type": "state",
      "family": "asic",
      "keyword": "Buy ASIC Miner in New Mexico"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-nevada",
        "keyword": "Buy ASIC Miner in Nevada"
      },
      {
        "slug": "buy-asic-miner-in-new-hampshire",
        "keyword": "Buy ASIC Miner in New Hampshire"
      },
      {
        "slug": "buy-asic-miner-in-new-jersey",
        "keyword": "Buy ASIC Miner in New Jersey"
      },
      {
        "slug": "buy-asic-miner-in-new-york",
        "keyword": "Buy ASIC Miner in New York"
      },
      {
        "slug": "buy-asic-miner-in-north-carolina",
        "keyword": "Buy ASIC Miner in North Carolina"
      },
      {
        "slug": "buy-asic-miner-in-north-dakota",
        "keyword": "Buy ASIC Miner in North Dakota"
      },
      {
        "slug": "buy-asic-miner-in-ohio",
        "keyword": "Buy ASIC Miner in Ohio"
      },
      {
        "slug": "buy-antminer-z15-pro-in-new-mexico",
        "keyword": "Buy Antminer Z15 Pro in New Mexico"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-new-mexico",
        "keyword": "Buy Bitmain Antminer S23 in New Mexico"
      },
      {
        "slug": "buy-antminer-z15-pro-in-connecticut",
        "keyword": "Buy Antminer Z15 Pro in Connecticut"
      },
      {
        "slug": "buy-antminer-z15-pro-in-delaware",
        "keyword": "Buy Antminer Z15 Pro in Delaware"
      },
      {
        "slug": "buy-antminer-z15-pro-in-florida",
        "keyword": "Buy Antminer Z15 Pro in Florida"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-red-deer",
      "place": "Red Deer",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-grande-prairie",
        "keyword": "Buy ASIC Miner in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-albert",
        "keyword": "Buy ASIC Miner in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-abbotsford",
        "keyword": "Buy ASIC Miner in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-burnaby",
        "keyword": "Buy ASIC Miner in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-coquitlam",
        "keyword": "Buy ASIC Miner in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-johns",
        "keyword": "Buy Antminer Z15 Pro in St. John's, Newfoundland and Labrador, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-dartmouth",
        "keyword": "Buy Antminer Z15 Pro in Dartmouth, Nova Scotia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-halifax",
        "keyword": "Buy Antminer Z15 Pro in Halifax, Nova Scotia, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-brantford",
      "place": "Brantford",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Brantford, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-airdrie",
        "keyword": "Buy ASIC Miner in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-calgary",
        "keyword": "Buy ASIC Miner in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-edmonton",
        "keyword": "Buy ASIC Miner in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-grande-prairie",
        "keyword": "Buy ASIC Miner in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brantford",
        "keyword": "Buy Antminer Z15 Pro in Brantford, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-brantford",
        "keyword": "Buy Bitmain Antminer S23 in Brantford, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-iqaluit",
        "keyword": "Buy ASIC Miner in Iqaluit, Nunavut, Canada"
      },
      {
        "slug": "buy-asic-miner-in-whitehorse",
        "keyword": "Buy ASIC Miner in Whitehorse, Yukon, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-airdrie",
        "keyword": "Buy Bitmain Antminer S23 in Airdrie, Alberta, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-richmond-hill",
      "place": "Richmond Hill",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Richmond Hill, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-albert",
        "keyword": "Buy ASIC Miner in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-abbotsford",
        "keyword": "Buy ASIC Miner in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-burnaby",
        "keyword": "Buy ASIC Miner in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-coquitlam",
        "keyword": "Buy ASIC Miner in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-richmond-hill",
        "keyword": "Buy Antminer Z15 Pro in Richmond Hill, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-richmond-hill",
        "keyword": "Buy Bitmain Antminer S23 in Richmond Hill, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-nanaimo",
        "keyword": "Buy Antminer Z15 Pro in Nanaimo, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-prince-george",
        "keyword": "Buy Antminer Z15 Pro in Prince George, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-richmond",
        "keyword": "Buy Antminer Z15 Pro in Richmond, British Columbia, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-st-catharines",
      "place": "St. Catharines",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in St. Catharines, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-nanaimo",
        "keyword": "Buy ASIC Miner in Nanaimo, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-prince-george",
        "keyword": "Buy ASIC Miner in Prince George, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-richmond",
        "keyword": "Buy ASIC Miner in Richmond, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-surrey",
        "keyword": "Buy ASIC Miner in Surrey, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-vancouver",
        "keyword": "Buy ASIC Miner in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-victoria",
        "keyword": "Buy ASIC Miner in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-brandon",
        "keyword": "Buy ASIC Miner in Brandon, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-catharines",
        "keyword": "Buy Antminer Z15 Pro in St. Catharines, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-catharines",
        "keyword": "Buy Bitmain Antminer S23 in St. Catharines, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-yorkton",
        "keyword": "Buy Antminer Z15 Pro in Yorkton, Saskatchewan, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-yellowknife",
        "keyword": "Buy Antminer Z15 Pro in Yellowknife, Northwest Territories, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-iqaluit",
        "keyword": "Buy Antminer Z15 Pro in Iqaluit, Nunavut, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-montréal",
      "place": "Montréal",
      "country": "Canada",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Montréal, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-grande-prairie",
        "keyword": "Buy ASIC Miner in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-lethbridge",
        "keyword": "Buy ASIC Miner in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-medicine-hat",
        "keyword": "Buy ASIC Miner in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-albert",
        "keyword": "Buy ASIC Miner in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-abbotsford",
        "keyword": "Buy ASIC Miner in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-burnaby",
        "keyword": "Buy ASIC Miner in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montréal",
        "keyword": "Buy Antminer Z15 Pro in Montréal, Quebec, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-montréal",
        "keyword": "Buy Bitmain Antminer S23 in Montréal, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-vancouver",
        "keyword": "Buy ASIC Miner in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-victoria",
        "keyword": "Buy ASIC Miner in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-asic-miner-in-brandon",
        "keyword": "Buy ASIC Miner in Brandon, Manitoba, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-chichester",
      "place": "Chichester",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Chichester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-carlisle",
        "keyword": "Buy ASIC Miner in Carlisle, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chelmsford",
        "keyword": "Buy ASIC Miner in Chelmsford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-chester",
        "keyword": "Buy ASIC Miner in Chester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-colchester",
        "keyword": "Buy ASIC Miner in Colchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-coventry",
        "keyword": "Buy ASIC Miner in Coventry, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-derby",
        "keyword": "Buy ASIC Miner in Derby, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-doncaster",
        "keyword": "Buy ASIC Miner in Doncaster, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-chichester",
        "keyword": "Buy Antminer Z15 Pro in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-chichester",
        "keyword": "Buy Bitmain Antminer S23 in Chichester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-londonderry",
        "keyword": "Buy Bitmain Antminer S23 in Londonderry, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-newry",
        "keyword": "Buy Bitmain Antminer S23 in Newry, Northern Ireland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-bath",
        "keyword": "Buy Antminer Z15 Pro in Bath, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-newcastle-upon-tyne",
      "place": "Newcastle upon Tyne",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Newcastle upon Tyne, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-liverpool",
        "keyword": "Buy ASIC Miner in Liverpool, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-manchester",
        "keyword": "Buy ASIC Miner in Manchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-milton-keynes",
        "keyword": "Buy ASIC Miner in Milton Keynes, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-norwich",
        "keyword": "Buy ASIC Miner in Norwich, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-nottingham",
        "keyword": "Buy ASIC Miner in Nottingham, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-oxford",
        "keyword": "Buy ASIC Miner in Oxford, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-plymouth",
        "keyword": "Buy ASIC Miner in Plymouth, England, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-newcastle-upon-tyne",
        "keyword": "Buy Antminer Z15 Pro in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-newcastle-upon-tyne",
        "keyword": "Buy Bitmain Antminer S23 in Newcastle upon Tyne, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-aberdeen",
        "keyword": "Buy Bitmain Antminer S23 in Aberdeen, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-dundee",
        "keyword": "Buy Bitmain Antminer S23 in Dundee, Scotland, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-dunfermline",
        "keyword": "Buy Bitmain Antminer S23 in Dunfermline, Scotland, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-asic-miner-in-winchester",
      "place": "Winchester",
      "country": "United Kingdom",
      "type": "city",
      "family": "asic",
      "keyword": "Buy ASIC Miner in Winchester, England, United Kingdom"
    },
    "related": [
      {
        "slug": "buy-asic-miner-in-wakefield",
        "keyword": "Buy ASIC Miner in Wakefield, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-wells",
        "keyword": "Buy ASIC Miner in Wells, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-westminster",
        "keyword": "Buy ASIC Miner in Westminster, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-wolverhampton",
        "keyword": "Buy ASIC Miner in Wolverhampton, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-worcester",
        "keyword": "Buy ASIC Miner in Worcester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-york",
        "keyword": "Buy ASIC Miner in York, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-aberdeen",
        "keyword": "Buy ASIC Miner in Aberdeen, Scotland, United Kingdom"
      },
      {
        "slug": "buy-antminer-z15-pro-in-winchester",
        "keyword": "Buy Antminer Z15 Pro in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-winchester",
        "keyword": "Buy Bitmain Antminer S23 in Winchester, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-southend-on-sea",
        "keyword": "Buy ASIC Miner in Southend-on-Sea, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-st-albans",
        "keyword": "Buy ASIC Miner in St Albans, England, United Kingdom"
      },
      {
        "slug": "buy-asic-miner-in-stoke-on-trent",
        "keyword": "Buy ASIC Miner in Stoke-on-Trent, England, United Kingdom"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-minnesota",
      "place": "Minnesota",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Minnesota"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-maryland",
        "keyword": "Buy Bitmain Antminer S23 in Maryland"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-massachusetts",
        "keyword": "Buy Bitmain Antminer S23 in Massachusetts"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-michigan",
        "keyword": "Buy Bitmain Antminer S23 in Michigan"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-mississippi",
        "keyword": "Buy Bitmain Antminer S23 in Mississippi"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-missouri",
        "keyword": "Buy Bitmain Antminer S23 in Missouri"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-montana",
        "keyword": "Buy Bitmain Antminer S23 in Montana"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nebraska",
        "keyword": "Buy Bitmain Antminer S23 in Nebraska"
      },
      {
        "slug": "buy-antminer-z15-pro-in-minnesota",
        "keyword": "Buy Antminer Z15 Pro in Minnesota"
      },
      {
        "slug": "buy-asic-miner-in-minnesota",
        "keyword": "Buy ASIC Miner in Minnesota"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-south-dakota",
        "keyword": "Buy Bitmain Antminer S23 in South Dakota"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-tennessee",
        "keyword": "Buy Bitmain Antminer S23 in Tennessee"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-texas",
        "keyword": "Buy Bitmain Antminer S23 in Texas"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-pennsylvania",
      "place": "Pennsylvania",
      "country": "United States",
      "type": "state",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Pennsylvania"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-ohio",
        "keyword": "Buy Bitmain Antminer S23 in Ohio"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-oklahoma",
        "keyword": "Buy Bitmain Antminer S23 in Oklahoma"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-oregon",
        "keyword": "Buy Bitmain Antminer S23 in Oregon"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-rhode-island",
        "keyword": "Buy Bitmain Antminer S23 in Rhode Island"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-south-carolina",
        "keyword": "Buy Bitmain Antminer S23 in South Carolina"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-south-dakota",
        "keyword": "Buy Bitmain Antminer S23 in South Dakota"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-tennessee",
        "keyword": "Buy Bitmain Antminer S23 in Tennessee"
      },
      {
        "slug": "buy-antminer-z15-pro-in-pennsylvania",
        "keyword": "Buy Antminer Z15 Pro in Pennsylvania"
      },
      {
        "slug": "buy-asic-miner-in-pennsylvania",
        "keyword": "Buy ASIC Miner in Pennsylvania"
      },
      {
        "slug": "buy-antminer-z15-pro-in-south-carolina",
        "keyword": "Buy Antminer Z15 Pro in South Carolina"
      },
      {
        "slug": "buy-antminer-z15-pro-in-south-dakota",
        "keyword": "Buy Antminer Z15 Pro in South Dakota"
      },
      {
        "slug": "buy-antminer-z15-pro-in-tennessee",
        "keyword": "Buy Antminer Z15 Pro in Tennessee"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-red-deer",
      "place": "Red Deer",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-coquitlam",
        "keyword": "Buy Bitmain Antminer S23 in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-red-deer",
        "keyword": "Buy Antminer Z15 Pro in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-asic-miner-in-red-deer",
        "keyword": "Buy ASIC Miner in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-toronto",
        "keyword": "Buy Bitmain Antminer S23 in Toronto, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-vaughan",
        "keyword": "Buy Bitmain Antminer S23 in Vaughan, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-waterloo",
        "keyword": "Buy Bitmain Antminer S23 in Waterloo, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-mount-pearl",
      "place": "Mount Pearl",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Mount Pearl, Newfoundland and Labrador, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-mount-pearl",
        "keyword": "Buy Antminer Z15 Pro in Mount Pearl, Newfoundland and Labrador, Canada"
      },
      {
        "slug": "buy-asic-miner-in-mount-pearl",
        "keyword": "Buy ASIC Miner in Mount Pearl, Newfoundland and Labrador, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-langley",
        "keyword": "Buy Bitmain Antminer S23 in Langley, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-nanaimo",
        "keyword": "Buy Bitmain Antminer S23 in Nanaimo, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-prince-george",
        "keyword": "Buy Bitmain Antminer S23 in Prince George, British Columbia, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-brantford",
      "place": "Brantford",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Brantford, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-airdrie",
        "keyword": "Buy Bitmain Antminer S23 in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-calgary",
        "keyword": "Buy Bitmain Antminer S23 in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-edmonton",
        "keyword": "Buy Bitmain Antminer S23 in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brantford",
        "keyword": "Buy Antminer Z15 Pro in Brantford, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-brantford",
        "keyword": "Buy ASIC Miner in Brantford, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-kingston",
        "keyword": "Buy ASIC Miner in Kingston, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-kitchener",
        "keyword": "Buy ASIC Miner in Kitchener, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-london",
        "keyword": "Buy ASIC Miner in London, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-richmond-hill",
      "place": "Richmond Hill",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Richmond Hill, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-coquitlam",
        "keyword": "Buy Bitmain Antminer S23 in Coquitlam, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-richmond-hill",
        "keyword": "Buy Antminer Z15 Pro in Richmond Hill, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-richmond-hill",
        "keyword": "Buy ASIC Miner in Richmond Hill, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-trois-rivières",
        "keyword": "Buy ASIC Miner in Trois-Rivières, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-moose-jaw",
        "keyword": "Buy ASIC Miner in Moose Jaw, Saskatchewan, Canada"
      },
      {
        "slug": "buy-asic-miner-in-prince-albert",
        "keyword": "Buy ASIC Miner in Prince Albert, Saskatchewan, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-st-catharines",
      "place": "St. Catharines",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in St. Catharines, Ontario, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-nanaimo",
        "keyword": "Buy Bitmain Antminer S23 in Nanaimo, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-prince-george",
        "keyword": "Buy Bitmain Antminer S23 in Prince George, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-richmond",
        "keyword": "Buy Bitmain Antminer S23 in Richmond, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-surrey",
        "keyword": "Buy Bitmain Antminer S23 in Surrey, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-vancouver",
        "keyword": "Buy Bitmain Antminer S23 in Vancouver, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-victoria",
        "keyword": "Buy Bitmain Antminer S23 in Victoria, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-brandon",
        "keyword": "Buy Bitmain Antminer S23 in Brandon, Manitoba, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-st-catharines",
        "keyword": "Buy Antminer Z15 Pro in St. Catharines, Ontario, Canada"
      },
      {
        "slug": "buy-asic-miner-in-st-catharines",
        "keyword": "Buy ASIC Miner in St. Catharines, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-sault-ste-marie",
        "keyword": "Buy Bitmain Antminer S23 in Sault Ste. Marie, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-sudbury",
        "keyword": "Buy Bitmain Antminer S23 in Sudbury, Ontario, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-thunder-bay",
        "keyword": "Buy Bitmain Antminer S23 in Thunder Bay, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-gatineau",
      "place": "Gatineau",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Gatineau, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-airdrie",
        "keyword": "Buy Bitmain Antminer S23 in Airdrie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-calgary",
        "keyword": "Buy Bitmain Antminer S23 in Calgary, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-edmonton",
        "keyword": "Buy Bitmain Antminer S23 in Edmonton, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-gatineau",
        "keyword": "Buy Antminer Z15 Pro in Gatineau, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-gatineau",
        "keyword": "Buy ASIC Miner in Gatineau, Quebec, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kingston",
        "keyword": "Buy Antminer Z15 Pro in Kingston, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-kitchener",
        "keyword": "Buy Antminer Z15 Pro in Kitchener, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-london",
        "keyword": "Buy Antminer Z15 Pro in London, Ontario, Canada"
      }
    ]
  },
  {
    "loc": {
      "slug": "buy-bitmain-antminer-s23-in-montréal",
      "place": "Montréal",
      "country": "Canada",
      "type": "city",
      "family": "s23",
      "keyword": "Buy Bitmain Antminer S23 in Montréal, Quebec, Canada"
    },
    "related": [
      {
        "slug": "buy-bitmain-antminer-s23-in-grande-prairie",
        "keyword": "Buy Bitmain Antminer S23 in Grande Prairie, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-lethbridge",
        "keyword": "Buy Bitmain Antminer S23 in Lethbridge, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-medicine-hat",
        "keyword": "Buy Bitmain Antminer S23 in Medicine Hat, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-red-deer",
        "keyword": "Buy Bitmain Antminer S23 in Red Deer, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-st-albert",
        "keyword": "Buy Bitmain Antminer S23 in St. Albert, Alberta, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-abbotsford",
        "keyword": "Buy Bitmain Antminer S23 in Abbotsford, British Columbia, Canada"
      },
      {
        "slug": "buy-bitmain-antminer-s23-in-burnaby",
        "keyword": "Buy Bitmain Antminer S23 in Burnaby, British Columbia, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-montréal",
        "keyword": "Buy Antminer Z15 Pro in Montréal, Quebec, Canada"
      },
      {
        "slug": "buy-asic-miner-in-montréal",
        "keyword": "Buy ASIC Miner in Montréal, Quebec, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-barrie",
        "keyword": "Buy Antminer Z15 Pro in Barrie, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brampton",
        "keyword": "Buy Antminer Z15 Pro in Brampton, Ontario, Canada"
      },
      {
        "slug": "buy-antminer-z15-pro-in-brantford",
        "keyword": "Buy Antminer Z15 Pro in Brantford, Ontario, Canada"
      }
    ]
  }
];
